### ISSUE TITLE
Possibilty to support by donation

### ISSUE THREAD

**Issue by liams239** [runely/calendar-homey#106]
Hi @runely ,

I don't find any possibilty to donate for your hard and fast work in this great app.

Is it possible somewhere?

Kind regards,

Liam

**Comment by runely** [comment]
Hi, and thanks for the good feedback 🥇 

I have not even thought of having a donation possibility. I might look into it 👍

**Comment by liams239** [comment]
Hi, 
Very good!

**Comment by runely** [comment]
I have added a donation button at the bottom of the readme page on GitHub, although i feel it's not really necessary

**Comment by liams239** [comment]
Okay, Necessary is a big word :) . But hard and good work is always appreciated not only by me ;). And it is always nice that we can show the appreciation and you see it 😁
