### ISSUE TITLE
Read calendar after trigger

### ISSUE THREAD

**Issue by JPe2** [runely/calendar-homey#109]
hi Runely, I would like to be able to let Homey read all agenda items of current day after a trigger from my PIR sensor in the livingroom firsttime in the morning. Is it possible to add such a "read all items of the day" function to this very nice app? Thanks in advance. 

PS. Are "reminders" in the agenda also possible in the future?

**Comment by runely** [comment]
Hi @JPe2, and thanks for the feedback!

There is a [global token](https://github.com/runely/calendar-homey#global-flow-tokens-can-be-used-in-any-app-and-service) called **Todays events, title and time** which contains all agenda items on your **calendars** todays. You also have the option to use **Todays events (per calendar)** if you only want todays events for a specific calendar.

Combine the global token with a TTS service (like Google TTS) 👍 

What use case do you need the reminders for? By using the triggers and/or conditions from this app, along with all other possibilities from Homey, i haven't seen any use for this.

**Comment by JPe2** [comment]
Hi Rune,
Thanks or your reply, but my problem is, I can't find how to get the global
tokens *Todays events* into a flow, probably I oversee something, somewhere.
The only items I see in the Flow editor are: Triggers(3), Conditions(6) and
Actions(1) and the triggers have 6 tokens. What am I missing?

About the reminders, I use them in my calendar for some plants, I have to
water, every 3 weeks, no big deal if it is not there.

Jan Pekkeriet
Hoge Vijver 42
2923VP  Krimpen aan den IJssel
The Netherlands.
+31612677800
jan.pekkeriet@gmail.com



Op wo 19 aug. 2020 om 17:42 schreef Rune Moskvil Lyngås <
notifications@github.com>:

**Comment by runely** [comment]
[How to use tags in a flow](https://community.athom.com/t/how-to-use-tags-in-a-flow/9285)

**Comment by JPe2** [comment]
This was not the question, the question is: How to use Global Tokens?

**Comment by runely** [comment]
Global tags/tokens and tags/tokens for a trigger/condition are picked from the same place.

In a flow card click on the tag (🏷 ) icon which will bring up the list of all available tags. IcalCalendar's tags/tokens will be in there somewhere.

Please read up on how to use flows in Homey as this is the same procedure for all apps!

**Comment by JPe2** [comment]
Thank you, if it's there I'll find it.

Jan Pekkeriet
Hoge Vijver 42
2923VP  Krimpen aan den IJssel
+31612677800
jan.pekkeriet@gmail.com



Op wo 19 aug. 2020 om 19:30 schreef Rune Moskvil Lyngås <
notifications@github.com>:
