### ISSUE TITLE
xtra triggers

### ISSUE THREAD

**Issue by ehdegroot** [runely/calendar-homey#115]
Hey Rune,

first thank you for the update with my request! awesome! i now have the alarmclock working as i had before and even better :)

but i still have more requests ;)

is it possible to add more triggers? for example: next event in Calendar....( then show the multiple Calendars made in configuration) and without time duration, just next event...

the date in dutch is wrong. in my case it is now in english format: 08/29/20
officially we write our date as: 31-08-2020
Google TTS speaks it now out as: zero eight, twenty nine,  the twentiest
to correct this for tts, you could beter use: sathurday the 29th of august
or in dutch: zaterdag 29 augustus
however, i understand that you should have to make then a lot of options. maybe u can let this be a config setting?

**Comment by runely** [comment]
Hi, thats awesome!

Adding a trigger 'Event starts in calendar' has been on my backlog, so it's coming 😉

To have the option to choose the date format in settings is a good idea! I'll look into it 👍

**Comment by runely** [comment]
In the next release:

- There's a new trigger: **Event starts from calendar** where you can choose calendar to get started events from.

- Dutch date format is fixed

- Date and time format can now be chosen freely (almost) in the settings

**Comment by RobHomey** [comment]
Hi Rune,

Do you put this first in test of just release it?
If it is in test first, I am able to update the tutorial.

Kind regards,
Rob

**Comment by runely** [comment]
When the new release is finished, i will create it as test first so you can test it and update the tutorial 👍
