### ISSUE TITLE
Show duration of event not only in hours

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [runely/calendar-homey#137]
Show duration of event not only in hours. But also in days and weeks and months.

For example, I have an event from Tuesday till Saturday, It will tell me that the event starts tomorrow and has a duration of 120 hours.  It would be very nice to see this calculated into 5 days and if larger than 5 days, shown in weeks and if more than 4 weeks in months.

Thanks in advance!

Marco

**Comment by runely** [comment]
That a good idea! I'll check it out!

**Comment by runely** [comment]
This will be in the next release 👍

**Comment by MP-ICT-Diensten** [comment]
Thanks!


Met vriendelijke groet,


Marco Pietersma




Op ma 7 sep. 2020 om 21:16 schreef Rune Moskvil Lyngås <
notifications@github.com>:

**Comment by MP-ICT-Diensten** [comment]
Yes, it works 👍
