### ISSUE TITLE
Condition „Any Event ongoing“ does not work

### ISSUE THREAD

**Issue by dirkg173** [runely/calendar-homey#157]
If I choose „Any Event ongoing“ and in the calendar is a daily event, for example „Day of German unity“, than the result is false.
If I choose „Specific event ongoing“ and I choose a specific daily event, for example „Day of German unity“, than the result is true.
What is the problem? What I’m doing wrong?

Works not:
https://homey.app/f/gb8rLj/

Works:
https://homey.app/f/QuRuLj/

**Comment by runely** [comment]
Hi, and thanks for the report. This bug is already fixed for the next release, which was published to athom for control earlier today.

https://github.com/runely/calendar-homey/commit/3ae4845ed0135a83847d28606280a3912cf23884
