### ISSUE TITLE
Incorrect time after dst

### ISSUE THREAD

**Issue by runely** [runely/calendar-homey#166]
After dst some events have incorrect times

**Comment by jonorland** [comment]
Same for me. Now the events are trigger one hour before the event in the calendar.

**Comment by b-vb** [comment]
Seeing the same, all triggers are one hour early due to daylight saving time

**Comment by runely** [comment]
I've located where the timezone mismatch occurres and have a working version running on my Homey.

I will do some more tests locally before pushing a new version

**Comment by runely** [comment]
This is added in the next release
