### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by runely** [runely/calendar-homey#171]
A new setting is added that lets the user set the time frame ahead for events synced in.

@RobHomey 
Can you look over these files and translate the given line numbers to dutch?
- [Lines 42 and 43 translated and replaces lines 39 and 40](https://github.com/runely/calendar-homey/blob/b4bf6da849c30b4e142eab063531243f19204285/README.nl.txt#L41)
- [Lines 30-33 translated](https://github.com/runely/calendar-homey/blob/b4bf6da849c30b4e142eab063531243f19204285/locales/nl.json#L30)

**Comment by RobHomey** [comment]
Hi Runely,

For both files the requested translations are made.

Kind regards,
Rob

**Comment by runely** [comment]
Great. Thanks 👍
