### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by runely** [runely/calendar-homey#172]
A new setting is added that lets the user set the time frame ahead for events synced in.

@dirkg173 
Can you look over these files and translate the given line numbers to german?
- [Lines 42 and 43 translated and replaces lines 39 and 40](https://github.com/runely/calendar-homey/blob/b4bf6da849c30b4e142eab063531243f19204285/README.de.txt#L41)
- [Lines 30-33 translated](https://github.com/runely/calendar-homey/blob/b4bf6da849c30b4e142eab063531243f19204285/locales/de.json#L30)

**Comment by dirkg173** [comment]
Yes, I will and let you know.

**Comment by dirkg173** [comment]
Done.

**Comment by runely** [comment]
Great. Thanks  👍
