### ISSUE TITLE
Extension "Specific event is/isn't ongoing in calendar"

### ISSUE THREAD

**Issue by dirkg173** [runely/calendar-homey#189]
Hi @runely,
is it possible to ad the condition "**Specific** event !{{is|isn't}} ongoing in calendar"?
"Any event !{{is|isn't}} ongoing in calendar" does already exist.

Best regards
Dirk

**Comment by runely** [comment]
A "*Specific event !{{is|isn't}} ongoing in calendar*" would just be a copy of the already existing condition "*Specific event !{{is|isn't}} ongoing*". They would do the exact same thing, except that in the new condition you would also have to choose a calendar for no reason.

In the already existing condition you choose a specific event. And when you have chosen an event you have also indirectly chosen a calendar.

I'm sorry, but i see no point in adding this. What would this accomplish for you which you can't accomplish with the existing condition?

**Comment by dirkg173** [comment]
You are right, of course. The reason why I made this request is because "Specific event is running" does not list my calendar entry. But this was not well thought out.
But then I have another issue. Events in my Google Calendar and in my Apple Calendar are not shown when I want to use "Specific Event". But I'm sure that this worked before. I created the Apple Calendar just for testing and integrated it according to the instructions. After that I synchronized IcalCalender. The events are still not displayed.

**Comment by runely** [comment]
Are you sure Google and Apple calendars are synced? Can you see the events on https://calendar.google.com/calendar/ and https://www.icloud.com/calendar/ ?

And are the starttime of the events you want to select inside the time frame of 2 months (or the custom time frame you have set in settings)?

There was a bug, [fixed in v0.4.2](https://github.com/runely/calendar-homey/issues/170), which imported ALL non-recurring events. Even those further ahead than 2 months.

**Comment by dirkg173** [comment]
Hi Rune,
sorry for late reply. I will check it again and let you know.

**Comment by runely** [comment]
Are things working for you, or are you still missing events?

**Comment by dirkg173** [comment]
Yes, everything works fine now. I don't know why I had some problems before.
And of course there is no need to ad a action card with "Specific event !{{is|isn't}} ongoing in calendar".
Thank you for your support and patience.
