### ISSUE TITLE
Missing triggers on tasks

### ISSUE THREAD

**Issue by HarryKroezen** [runely/calendar-homey#193]
@runely, I had written this review:
Appointments works fine. If triggers also can be added to tasks? Then 5 stars

If possible, please add triggers to the tasks in the Google calendar.
As example:
![image](https://user-images.githubusercontent.com/75756644/101685231-cb319980-3a67-11eb-8fdc-c675ddca7744.png)

- The purple's are appointments and are working fine
- The green's are tasks and this items, I can't get this information in Homey

**Comment by runely** [comment]
As far as i can see, tasks lives in a separate calendar/list, which is not part of your primary calendar ical file.
I don't see any options to share the tasks calendar/list publicly as an ical file either.

If someone knows of another way, please let us know 👍 

Until tasks can be saved in your primary calendar or tasks calendar/list can be shared publicly, tasks will not be possible to import to Homey.
