### ISSUE TITLE
Custom date format yield invalid date format string

### ISSUE THREAD

**Issue by Shakesbeard** [runely/calendar-homey#195]
Hey there,
I tried to use YYYY/MM/DD for the date format but that is not accepted.
I tried some variantions but in the end it accepted the default format only.

**Comment by runely** [comment]
Hey. You are correct. I'm from Scandinavia where the date format is `DD/MM/YYYY`. I did add support for `MM/DD/YYYY`, but i forgot about `YYYY/MM/DD`.

It will be fixed in the next release 👍

**Comment by Shakesbeard** [comment]
Thanks a bunch
