### ISSUE TITLE
Icalcalendar app doesn’t sync in ongoing regular events

### ISSUE THREAD

**Issue by papounet-git** [runely/calendar-homey#199]
Hello,
I’m running 0.5.0 version on Homey. My Icalcalendar app only detects the next event in my public calendar but not the ongoing one. I can see it from the tag values e.g. today’s event count = 0 or due to the fact some flow depending on events don’t behave properly.
This used to work correctly not so long ago... I didn’t change any setup on icalcalendar app recently.
Could you please help?
Thanks in advance

**Comment by papounet-git** [comment]
I’ve of course already tried to restart the app, Homey device... and added multiple calendars and entries, but still only the next future events are detected.

**Comment by runely** [comment]
This works as it should on my Homey.

I tested it by:
* Creating a new event with start time 5 minutes ahead.
* Synced the new event in by manually running the action card "Sync calendars".
* I confirmed that the next event was the newly created event
* Waited until the event started
* Then added the conditions "Any event is ongoing" and "Specific event is ongoing" and chose the newly created event for this condition.
* Tested the flow and both conditions worked as they should.

When an event has started, that event will no longer be listed as the next event. It will however be listed in the following tags (as long as it hasn't ended yet):
* Todays events, title and time
* Todays events (count)
* Todays events in %calendarname%

The next event tag will at all times contain the next event to start (provided the next events start time is inside the time frame synced in)

**Comment by papounet-git** [comment]
Thanks runely. In my case, none of the Today’s tags are populated
![43240F42-CEDA-4ACF-BD9E-9E22BB422EB0](https://user-images.githubusercontent.com/76526236/103026326-f205ca80-4553-11eb-9ed5-3be4100bb27c.jpeg)
I’m using default icalcalendar parameters.

**Comment by runely** [comment]
Ahh, i see what you mean. Ongoing regular events is not synced in. I will fix this in the next release 👍

**Comment by papounet-git** [comment]
Thanks, happy to test the fix when you’ll release it.

**Comment by runely** [comment]
New version is sent to homey for verification. If you want to test this version before it's certified, you can install the test version from here: https://homey.app/a/no.runely.calendar/test

**Comment by papounet-git** [comment]
I confirm it fixed the issue. Well done !
