### ISSUE TITLE
Getting an error popup constantly

### ISSUE THREAD

**Issue by Robinyoh** [runely/calendar-homey#216]
**Describe the bug**
Getting an error popup constantly when go to "configure app"

**To Reproduce**
1. Go to 'configure app'
2. See error

**Expected behavior**

**Screenshots**

**Homey:**
 - Firmware: 5.0
 - IcalCalendar version: 0.6.3

**Additional context**
![IMG_8606](https://user-images.githubusercontent.com/18645811/108636368-0d725080-7485-11eb-9fe7-e21ec0d4403a.PNG)

**Comment by runely** [comment]
Hi.

I was able to reproduce this on my Homey v5.0.0.

This is only applicable for new app installs on Homey v5.0.0. This happens because Homey has changed the way non-existing app settings are returned.

This is fixed in the next release

**Comment by Robinyoh** [comment]
Thx for the quick fix!
