### ISSUE TITLE
Recurring events can't handle crossing over to next day

### ISSUE THREAD

**Issue by torbmelb88** [runely/calendar-homey#218]
**Describe the bug**
Recurring/repeating events, starting one day, and ends on another day, dissapers from homey at midnight after the event starts. This causes triggers on event end not to function.

**To Reproduce**
1. Create repeating event in Google calendar that extends into the next day.
2. Create flow in homey that triggers on said events end time.

**Homey:**
 - Firmware: 5.0.0
 - IcalCalendar version: 0.6.4

**Comment by runely** [comment]
https://community.athom.com/t/tutotial-trigger-a-flow-using-calendar-events/34017/8?u=runely

https://community.athom.com/t/tutotial-trigger-a-flow-using-calendar-events/34017/10?u=runely
