### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Rens-H** [runely/calendar-homey#251]
What I would like to see when an event has been rescheduled that I can trigger something within homey.
Example, someone has changed a meeting time or date or a location.

**Comment by runely** [comment]
I've added a `Event changed` trigger in test release **0.9.0**. This trigger card will be triggered after calendars are synchronized (every 15 minutes or when action card `Sync calendars` are executed) and any of the previous synchronized calendar events have been changed

Would you test the release and let me know what you think? https://homey.app/no-no/app/no.runely.calendar/IcalCalendar/test/

**Comment by Rens-H** [comment]
Hey,

Thanks, I will test it and let you know.


Rens

Op zo 31 okt. 2021 om 21:33 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by Rens-H** [comment]
Hey Looks like it is working as expected, I can trigger something when a
item has changed to another time for example.

Thank you for your fast response :-)

Op di 2 nov. 2021 om 09:56 schreef Rens Hoekema ***@***.***>:

**Comment by runely** [comment]
This will be released in `v0.9.1` when its reviewed successfully by Athom
