### ISSUE TITLE
Is it possible to use wildcards in the select event

### ISSUE THREAD

**Issue by DJranty** [runely/calendar-homey#253]
**Is your feature request related to a problem? Please describe.**
To use exact values in events starts you need to dynamically adjut the flows all the time, I would prefer a dynamic approach

**Describe the solution you'd like**
The use of wild cards in the event strats in xx time. This way I could use that card in the "if" section. Example. Event starts in 15 minutes and contains "Teams". I then can follow up card with accurate actions, such as adjust lights to office mode etc.

**Describe alternatives you've considered**
No alternatives yet.

**Additional context**

**Comment by runely** [comment]
If i understand you correctly, there's no need to have a separate trigger for this.

Use the trigger `Event starts in` in the **if** section and then use `Logic -> Token contains` in the **And** section to check if `Title` token from the trigger contains `Teams`

**Comment by runely** [comment]
Is this a viable solution?

**Comment by DJranty** [comment]
Yes, thanks, I just stumbled on that logic as well :-)
