### ISSUE TITLE
Bug: Invalid time value error

### ISSUE THREAD

**Issue by hfaas** [runely/calendar-homey#266]
**Describe the bug**
Lately (probably since one of the recent updates), my ical is not processed anymore. Or at least it is giving an error when parsing the calendar info.

I've tried regenerating a new ICAL url and reinserting it in Homey, but it keeps throwing an error:
"Invalid Time Value"

**To Reproduce**
I'm not sure how te reproduce. What might be of interest is, that it is an outlook calendar.

If you do need additional info or a link to the calendar, please let me know.

1. Insert link in homey
2. Scroll down to the end of the ical settings
4. Notice the error "<calander name>: Invalid time value"

**Expected behavior**
Obviously no error?!

**Screenshots**
![image](https://user-images.githubusercontent.com/1212614/143076981-7dac8ddf-4b8f-4865-ad17-c9147fc6a216.png)

**Homey:**
 - Firmware: 7.1.6
 - IcalCalendar version: 0.9.2

**Additional context**
Although the settings page of the app consistently throws an error, the flows using the events does still sometimes seem to work. That is making it confusing!

I'm still figuring out whether some of the data is still being read or that it is "cached" data from before, that is triggering the flows.

**Comment by runely** [comment]
The `Invalid time value` is an exception thrown when your calendar `Thuiswerk kalender` is parsed. Somewhere in that calendar there’s a date/time value it’s not happy with.

Can you run your calendar through [this validator](https://icalendar.org/validator.html) to see if there’s any obvious errors?

**Comment by hfaas** [comment]
The validator helped for finding a duplicate UID, between a single event and a reoccurring event.

However the issue with Invalid time value is still thrown.

I did notice the validator is mentioning there are 2 timezones defined (probably because the events are entered from 2 different phones), but it says it is all parsed successfully without errors, while the Ical app still complains.

**Comment by hfaas** [comment]
After removing a few (reoccurring) events from the past (this summer) it seems to be working again.

Could it be that there is a conflict with timezones and Daylight saving (which is always a pain in dealing with calendars)?

**Comment by runely** [comment]
In my calendar there’s 3 `VTIMEZONE` entries, so i don’t think that is the problem.

I'm glad that removing some entries made it work again.

But out of curiosity it would be very helpful if you could mail me your calendar url (must contain the events causing this error) so i can investigate why this is happening.

You can mail the url to [runeutvikler@gmail.com](mailto:runeutvikler@gmail.com)

**Comment by hfaas** [comment]
I'd love to share the calendar, but unfortunately I can't find/recover the removed events.

I'm afraid we have to wait until it "fails" again, unless you know a way to how to recover the events do this?

**Comment by runely** [comment]
Don't know if that is possible.

I'll close this issue for now. Post back in this issue if the problem reoccurs
