### ISSUE TITLE
Invalid time value

### ISSUE THREAD

**Issue by Blaxtar** [runely/calendar-homey#272]
**Describe the bug**
No Mather how I try I get the error message "Failed to load .ics file(s): [Calendar name]: Invalid time value.
I've tried all combinations of date and time format in the app settings and in outlook web calendar but can't get it to work. Please help :-/

**Screenshots**
![IMG_DE9C8D57879E-1](https://user-images.githubusercontent.com/10800521/149252879-def7cf7f-ebc2-4022-ad01-7d9c4ef03621.jpeg)
![Screen Shot 2022-01-13 at 03 01 34](https://user-images.githubusercontent.com/10800521/149252895-29186f3c-8a7f-41c2-97f6-6b517680e1fc.png)

**Homey:**
 - Firmware: 7.2.1
 - IcalCalendar version: 0.10.1

**Additional context**

**Comment by runely** [comment]
The `Invalid time value` is an exception thrown when your calendar `Familjen Thurfjell` is parsed. Somewhere in that calendar there’s a date/time value it’s not happy with.

Can you run your calendar through [this validator](https://icalendar.org/validator.html) to see if there’s any obvious errors?

Without any data there's not much i can do. If you find the event causing this problem i can check what’s happening.

**Comment by Blaxtar** [comment]
Thanks for taking time to help me! I've run it through the validator and it says "UID value is not unique, duplicate found near line # 57". I found the UID 040000008200E00074C5B7101A82E00800000000F5CFCDDD2F6FD701000000000000000 that exist multiple times on the following lines. What can I do to fix it?

Line 57-79
BEGIN:VEVENT
RRULE:FREQ=WEEKLY;UNTIL=20211213T120000Z;INTERVAL=1;BYDAY=MO;WKST=MO
UID:040000008200E00074C5B7101A82E00800000000F5CFCDDD2F6FD701000000000000000
 0100000001B391179B30C3D4D97FDDD2B9B7482F5
SUMMARY:Witts
DTSTART;TZID=Central Europe Standard Time:20211018T130000
DTEND;TZID=Central Europe Standard Time:20211018T170000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220115T002214Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:1
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

Line 572-594
BEGIN:VEVENT
UID:040000008200E00074C5B7101A82E00800000000F5CFCDDD2F6FD701000000000000000
 0100000001B391179B30C3D4D97FDDD2B9B7482F5
RECURRENCE-ID;TZID=Central Europe Standard Time:20211115T130000
SUMMARY:Witts (AVBOKAD)
DTSTART;TZID=Central Europe Standard Time:20211115T130000
DTEND;TZID=Central Europe Standard Time:20211115T170000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20220115T002214Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

**Comment by Blaxtar** [comment]
Nevermind, I found the event SUMMARY:Witts (AVBOKAD), DTSTART;TZID=Central Europe Standard Time:20211115T130000, DTEND;TZID=Central Europe Standard Time:20211115T170000 and just deleted it and now everything work flawless :-D

A question instead - how do I trigger a flow based on a recurring event? Is it possible to trig a event for example by name?

**Comment by runely** [comment]
> how do I trigger a flow based on a recurring event

All triggers, except `Event changed`, will trigger on your calendar events, both regular events and recurring events.

> Is it possible to trig a event for example by name

As above, use any of the triggers you see fit. All triggers has tokens letting you know which event is beeing triggered. You can then use a logic card in condition to check if the `Title` token is equal to the name you want to trigger on.

**Comment by Blaxtar** [comment]
You just solved my problem and teached me that logic might be used for conditions in apps, which I didn't knew before. A huge thank you from a country neighbor in Stockholm Sweden! Where is the "buy-me-beer-button"?x

**Comment by runely** [comment]
No need. Just glad to help 👍
