### ISSUE TITLE
Add trigger card which triggers every time a new event is created

### ISSUE THREAD

**Issue by joeblack2k** [runely/calendar-homey#273]
Hello Rune,

I have a question. I used to have a ifttt script that sends me a telegram message when a new Google Calender event was created but Athom decided to close ifttt communication. I was wondering if it could be possible with this plugin like for example:

If new event is created 
then telegram “new ‘event name’ ‘date’”

could that be done?

tusen takk!

**Comment by runely** [comment]
Just to be sure, you would like a trigger card which triggers every time a new event is created?

I do see some potential problems here.
- The app updates all calendars every 15 minutes. Such a trigger would not trigger immediately when you created an event, but up to 15 minutes after the creation time
- To be able to trigger correctly, the app should then check if there are any new events that have been created within the last 15 minutes. If something goes wrong here, network problems, or anything else, the trigger will not be triggered for this event

The trigger card can be implemted if this is acceptable.

**Comment by joeblack2k** [comment]
Yes that sounds acceptable! The second potential is fine but wouldn’t it be triggered anyways because the sync sees difference between versions ? Like if you pull the Homey plug and after a day you plug it back it would sync (and see) the events created in the downtime and trigger multiple times? If that it’s not the case it’s also fine! Thanks allot!

**Comment by runely** [comment]
I have released a new version to test [v0.13.0](https://homey.app/a/no.runely.calendar/test/). Could you please install this and test it out and let me know how it's working for you?

**Comment by runely** [comment]
v0.13.1 is released to the Homey Store

**Comment by joeblack2k** [comment]
it works perfectly thank you so much!!
