### ISSUE TITLE
After the update to version 0.11.0, I got an error

### ISSUE THREAD

**Issue by HarryKroezen** [runely/calendar-homey#275]
**Describe the bug**
After the update to versoion 0.11.0, I got an error and the calendar isn't loaded.

**To Reproduce**
1. Go to Apps
2. Click on 'IcalCalender'
3. Click on 'Configure App'
3. Scroll down to '.End'
4. See error 'Error loading .ics file(s): <Name>: "DTSTART", "DTEND"' and/or "SUMMARY" is missing with UID: ...'

**Expected behavior**
The calendar is loaded, so that the flows can go off again to give notifications.

**Homey:**
 - Version: 7.2.1
 - App version: 6.11.0.854
 - IcalCalendar version: 0.11.0

**Additional informatie**
 - Yesterday, I have send you an diagnostic report: 5f627fe5-e091-410d-a0b0-7e69cbc1c721

**Comment by runely** [comment]
`summary` was "accidentally" made required for all events. Sorry about that!

Fixed in the next release

**Comment by runely** [comment]
v0.12.0 is released to the store
