### ISSUE TITLE
Feature: En avtale starter om X fra Y

### ISSUE THREAD

**Issue by SimonSkotheimsvik** [runely/calendar-homey#276]
Could add a When card for a new appointment in X minutes from a given calendar?
This will make new individuall possibillities for our household related to the personal calendars.

**Comment by runely** [comment]
This is already possible by combining trigger card `Event starts in` with a logic condition card checking the calendar name.

Or is there some use case where this will not suffice?

Example:
![image](https://user-images.githubusercontent.com/25814673/149680624-503dc2e9-c6e2-4ec3-99dc-339732c30b04.png)

**Comment by runely** [comment]
I'm guessing this is okey.

I'm closing this for now. Feel free to reopen this issue or comment here if this wasn't okay after all
