### ISSUE TITLE
Mailfence Ical don't sync properly

### ISSUE THREAD

**Issue by liams239** [runely/calendar-homey#28]
Hi,

I use mailfence as Calendar and it has the Ical function. I see some events but only a few items. The most of the items I see are from the past and are recurring events. 

In mailfence you have 2 settings for Ical:
You have a setting for iCal compatible software (but thats a secure page and in the homey app you can't enter a username or password). (link is like this: https://mailfence.com/docs/"USERNAME"/private/calendar.ics ).

And you have Public access link that's the one I use now but I can't see the most of the events.

Is it possbile to look into this? Maby when it is possible to enter the username and password it will sync properly?

Already thanks!,
Liam

**Comment by runely** [comment]
I had a quick look at the .ics file Mailfence presents and it looks like they are using a date time format which is not part of the iCalendar specification.

### Mailfence uses 
```text
DTSTART;VALUE=DATE-TIME:
```
or
```text
DTSTART;VALUE=DATE:
```

### iCalendar specification expects one of the following:
```text
DTSTART:19970714T133000
```
```text
DTSTART:19970714T173000Z
```
```text
DTSTART;TZID=US-Eastern:19970714T133000
```

Specifications found here: https://www.w3.org/2002/12/cal/rfc2445#sec4.3.5

## However
I do see some python and perle sites are using this unsupported format. I'll see if there is anything i can do.

**Comment by liams239** [comment]
> ## However
> 
> I do see some python and perle sites are using this unsupported format. I'll see if there is anything i can do.

Hi,
Okay thanks to clear that out. I hope that it is fixable. And thanks to see if you can fix it.

**Comment by runely** [comment]
Next release will have support for these formats as well:
```bash
DTSTART;VALUE=DATE-TIME
```
```bash
DTEND;VALUE=DATE-TIME
```
