### ISSUE TITLE
New event from search added (IFTTT style)

### ISSUE THREAD

**Issue by tedarg** [runely/calendar-homey#282]
Hello,
I'm looking for the possibility to do like IFTTT:
new event from search is added to your Google Calendar that contains a specific keyword or phrase. The search looks at the event's Title

**Comment by runely** [comment]
The description for trigger **New event from search added** at *IFTTT* states:

> This Trigger fires every time a new event from search is added to your Google Calendar that contains a specific keyword or phrase. The search looks at the event’s Title, Description, and Location

**IcalCalendar** has a trigger card for when a new event is added. However, this trigger card will only trigger when these requirements are met:
- The created events start time is inside the current datetime frame beeing synced in to the app (Start datetime is less than the datetime frame set in settings of **IcalCalendar** (*default is 2 months*)).
- The created event is created within the last 24 hours

This trigger card has the following tokens on it which you can use in a logic card in the **Conditions** part of the flow:
- Title
- Description
- Location
- Duration (in human readable form)
- Duration (in minutes)
- Calendar name
- Start date
- Start time
- End date
- End time

If i understood your request correctly, this will do it!
