### ISSUE TITLE
Feature: A short descriptive feature title here

### ISSUE THREAD

**Issue by joeblack2k** [runely/calendar-homey#283]
Would it be possible to add the tags:

DAY    e.g Monday
MONTH   e.g January 
DATE.  e.g 24

So I can have Alexa say “you have an event this DAY“ or “at DATE MONTH you have a meeting”

tusen takk! :)

**Comment by runely** [comment]
Thanks for the idea.

Is it global tags you mean? So you can use the tags no matter which trigger card is used.

Or tags for the trigger cards, so the tags are filled with data for the current event

**Comment by joeblack2k** [comment]
I think the data for the current event? I’ve uploaded my flow which I want to expand by adding DAY the day of the week so can quickly see wat event has been added :)



![1B3CF2CE-502F-4CAD-884B-F8D39CFD31AE](https://user-images.githubusercontent.com/3456102/151662306-d155c87e-113c-4708-98db-6264f79d8216.png)

**Comment by runely** [comment]
This is implemented in `v0.14.0` which is sent to Athom for review.
