### ISSUE TITLE
the iCal Homey app started to throw an error as of yesterday which I cannot seem to solve.

### ISSUE THREAD

**Issue by DJranty** [runely/calendar-homey#285]
**Describe the bug**
Importing events throws an invalid time value error

**To Reproduce**
Wait till the ical app starts to sync or amnually sync the events from your email account

**Expected behavior**

**Screenshots**
![Screenshot 2022-02-04 091545](https://user-images.githubusercontent.com/93655589/152495022-79bac085-3221-422a-8ef5-c7e96877313f.png)

**Homey:**
 - Firmware: 
 - IcalCalendar version: 0.14.0

**Additional context**
Any suggestions if this is not related to your code? So I can try to solve it from another angle.

**Comment by runely** [comment]
Hi. The `Invalid time value` is an exception thrown when your calendar `Ivanti` is parsed. Somewhere in that calendar there’s a date/time value it’s not happy with. You say this started yesterday, look up any new events created yesterday or so. Maybe even try to delete those events.

See these similar issues:
- https://github.com/runely/calendar-homey/issues/272
- https://github.com/runely/calendar-homey/issues/266

Let me know how it goes

**Comment by DJranty** [comment]
Okay, so the validator throws me an error of too large of file size
eventhough I am using the url of the ics. I even republished the agenda
just to be sure.

**Comment by runely** [comment]
Have you tried to remove any new events introduced the last couple of days?

If that helps try add one event at a time and see how it goes

**Comment by DJranty** [comment]
Well, problem is. It is my work mail. I use the ical app to schedule my
lights and media mute, unmute based on my agenda. So throwing out events is
not an option. It would help if I could investigate some how which events
cause a problem and why with that evaluator.

Op za 5 feb. 2022 00:06 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by runely** [comment]
The validator only handles ics files up to 512KB. Yours is probably bigger than that.

Without any data to test i can't help you.

I have a testing tool for ics files which simulates what the IcalCalendar app would do on Homey (only parsing and listing the calendar). You could give that a go and paste the error message printed.

https://github.com/runely/calendar-homey-test

**Comment by DJranty** [comment]
I followed the notes carefully (I never used npm or node.js before, only
powershell) and this is the error it has thrown. It basically does not run
correctly I think.



PS C:\temp\calendar-homey-test-master> npm run calendars

> ***@***.*** calendars
> node from-file.js

getEvents: Getting calendars: 1,

npm : C:\temp\calendar-homey-test-master\lib\calendarHomey\get-events.js:23
At line:1 char:1
+ npm run calendars
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified:
(C:\temp\calenda...et-events.js:23:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

        const isLocalFile = (options.isLocalFile !== undefined &&
options.isLocalFile) || false
                                     ^
TypeError: Cannot read properties of undefined (reading 'isLocalFile')
    at
C:\temp\calendar-homey-test-master\lib\calendarHomey\get-events.js:23:38
    at new Promise (<anonymous>)
    at module.exports
(C:\temp\calendar-homey-test-master\lib\calendarHomey\get-events.js:15:10)
    at Object.<anonymous>
(C:\temp\calendar-homey-test-master\from-file.js:18:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js
(node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain]
(node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

PS C:\temp\calendar-homey-test-master>

**Comment by runely** [comment]
Sorry. My mistake.. I forgot to update the **README** after i had changed the property `debugOptions` to just `options` in **calendars.json**.

To fix this rename the property `debugOptions` to `options` in your **calendars.json** file

**Comment by DJranty** [comment]
so running the script does not return errors for me (or I am reading this
wrong)


PS C:\temp\calendar-homey-test-master> npm run calendars

> ***@***.*** calendars
> node from-file.js

getEvents: Getting calendars: 1,

getEvents: Getting events (2 months ahead) for calendar 'Default' (
***@***.***/91f26deae5c54707
82ec6cd8e9e9daed18045996528596166342/calendar.ics)
get-ical-content(URL): Success getting data via node-ical:
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Feb
10 2022 08:30:00 GMT+0100' -- End: 'Thu Feb 10 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Feb
11 2022 08:30:00 GMT+0100' -- End: 'Fri Feb 11 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Feb
17 2022 08:30:00 GMT+0100' -- End: 'Thu Feb 17 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Feb
18 2022 08:30:00 GMT+0100' -- End: 'Fri Feb 18 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Feb
24 2022 08:30:00 GMT+0100' -- End: 'Thu Feb 24 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Feb
25 2022 08:30:00 GMT+0100' -- End: 'Fri Feb 25 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Mar
03 2022 08:30:00 GMT+0100' -- End: 'Thu Mar 03 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Mar
04 2022 08:30:00 GMT+0100' -- End: 'Fri Mar 04 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Mar
10 2022 08:30:00 GMT+0100' -- End: 'Thu Mar 10 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Mar
11 2022 08:30:00 GMT+0100' -- End: 'Fri Mar 11 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Mar
17 2022 08:30:00 GMT+0100' -- End: 'Thu Mar 17 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Mar
18 2022 08:30:00 GMT+0100' -- End: 'Fri Mar 18 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Mar
24 2022 08:30:00 GMT+0100' -- End: 'Thu Mar 24 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Mar
25 2022 08:30:00 GMT+0100' -- End: 'Fri Mar 25 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Thu Mar
31 2022 08:30:00 GMT+0200' -- End: 'Thu Mar 31 2022 09:30:00 GMT+0200' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Fri Apr
01 2022 08:30:00 GMT+0200' -- End: 'Fri Apr 01 2022 09:30:00 GMT+0200' --
TimezoneOffset: 'Fri
 Feb 05 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Feb 11 2022
17:00:00 GMT+0100' -- End: 'Fri Feb 11 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Feb 18 2022
17:00:00 GMT+0100' -- End: 'Fri Feb 18 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Feb 25 2022
17:00:00 GMT+0100' -- End: 'Fri Feb 25 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Mar 04 2022
17:00:00 GMT+0100' -- End: 'Fri Mar 04 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Mar 11 2022
17:00:00 GMT+0100' -- End: 'Fri Mar 11 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Mar 18 2022
17:00:00 GMT+0100' -- End: 'Fri Mar 18 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Mar 25 2022
17:00:00 GMT+0100' -- End: 'Fri Mar 25 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Fri Apr 01 2022
17:00:00 GMT+0200' -- End: 'Fri Apr 01 2022 18:00:00 GMT+0200' --
TimezoneOffset: 'Fri Feb 05 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Feb 10 2022
17:00:00 GMT+0100' -- End: 'Thu Feb 10 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Feb 17 2022
17:00:00 GMT+0100' -- End: 'Thu Feb 17 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Feb 24 2022
17:00:00 GMT+0100' -- End: 'Thu Feb 24 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Mar 03 2022
17:00:00 GMT+0100' -- End: 'Thu Mar 03 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Mar 10 2022
17:00:00 GMT+0100' -- End: 'Thu Mar 10 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Mar 17 2022
17:00:00 GMT+0100' -- End: 'Thu Mar 17 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Mar 24 2022
17:00:00 GMT+0100' -- End: 'Thu Mar 24 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Thu Mar 31 2022
17:00:00 GMT+0200' -- End: 'Thu Mar 31 2022 18:00:00 GMT+0200' --
TimezoneOffset: 'Thu Feb 11 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Mon Feb
14 2022 08:30:00 GMT+0100' -- End: 'Mon Feb 14 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Mon
 Feb 15 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Mon Feb
28 2022 08:30:00 GMT+0100' -- End: 'Mon Feb 28 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Mon
 Feb 15 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Mon Mar
14 2022 08:30:00 GMT+0100' -- End: 'Mon Mar 14 2022 09:30:00 GMT+0100' --
TimezoneOffset: 'Mon
 Feb 15 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids naar school brengen' -- Start: 'Mon Mar
28 2022 08:30:00 GMT+0200' -- End: 'Mon Mar 28 2022 09:30:00 GMT+0200' --
TimezoneOffset: 'Mon
 Feb 15 2021 09:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Mon Feb 14 2022
17:00:00 GMT+0100' -- End: 'Mon Feb 14 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Mon Feb 15 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Mon Feb 28 2022
17:00:00 GMT+0100' -- End: 'Mon Feb 28 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Mon Feb 15 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Mon Mar 14 2022
17:00:00 GMT+0100' -- End: 'Mon Mar 14 2022 18:00:00 GMT+0100' --
TimezoneOffset: 'Mon Feb 15 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Kids ophalen' -- Start: 'Mon Mar 28 2022
17:00:00 GMT+0200' -- End: 'Mon Mar 28 2022 18:00:00 GMT+0200' --
TimezoneOffset: 'Mon Feb 15 2021
 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Neurons Tiger Team' -- Start: 'Fri Feb 18
2022 11:30:00 GMT+0100' -- End: 'Fri Feb 18 2022 12:00:00 GMT+0100' --
TimezoneOffset: 'Fri Jun 1
1 2021 12:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'Neurons Tiger Team' -- Start: 'Fri Mar 04
2022 11:30:00 GMT+0100' -- End: 'Fri Mar 04 2022 12:00:00 GMT+0100' --
TimezoneOffset: 'Fri Jun 1
1 2021 12:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'Neurons Tiger Team' -- Start: 'Fri Mar 18
2022 11:30:00 GMT+0100' -- End: 'Fri Mar 18 2022 12:00:00 GMT+0100' --
TimezoneOffset: 'Fri Jun 1
1 2021 12:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'Neurons Tiger Team' -- Start: 'Fri Apr 01
2022 11:30:00 GMT+0200' -- End: 'Fri Apr 01 2022 12:00:00 GMT+0200' --
TimezoneOffset: 'Fri Jun 1
1 2021 12:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'EPM Team Huddle and Demos' -- Start: 'Tue
Feb 08 2022 23:30:00 GMT+0100' -- End: 'Wed Feb 09 2022 00:30:00 GMT+0100'
-- TimezoneOffset: 'Tu
e Aug 24 2021 16:30:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'EPM Team Huddle and Demos' -- Start: 'Tue
Mar 08 2022 23:30:00 GMT+0100' -- End: 'Wed Mar 09 2022 00:30:00 GMT+0100'
-- TimezoneOffset: 'Tu
e Aug 24 2021 16:30:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'EPM Team Huddle and Demos' -- Start: 'Tue
Apr 05 2022 23:30:00 GMT+0200' -- End: 'Wed Apr 06 2022 00:30:00 GMT+0200'
-- TimezoneOffset: 'Tu
e Aug 24 2021 16:30:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'ITxM EMEA SE Call (Bi-Weekly)' -- Start:
'Mon Feb 07 2022 17:00:00 GMT+0100' -- End: 'Mon Feb 07 2022 18:00:00
GMT+0100' -- TimezoneOffset:
 'Mon Sep 06 2021 17:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'ITxM EMEA SE Call (Bi-Weekly)' -- Start:
'Mon Feb 21 2022 17:00:00 GMT+0100' -- End: 'Mon Feb 21 2022 18:00:00
GMT+0100' -- TimezoneOffset:
 'Mon Sep 06 2021 17:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'ITxM EMEA SE Call (Bi-Weekly)' -- Start:
'Mon Mar 07 2022 17:00:00 GMT+0100' -- End: 'Mon Mar 07 2022 18:00:00
GMT+0100' -- TimezoneOffset:
 'Mon Sep 06 2021 17:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'ITxM EMEA SE Call (Bi-Weekly)' -- Start:
'Mon Mar 21 2022 17:00:00 GMT+0100' -- End: 'Mon Mar 21 2022 18:00:00
GMT+0100' -- TimezoneOffset:
 'Mon Sep 06 2021 17:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: 'ITxM EMEA SE Call (Bi-Weekly)' -- Start:
'Mon Apr 04 2022 17:00:00 GMT+0200' -- End: 'Mon Apr 04 2022 18:00:00
GMT+0200' -- TimezoneOffset:
 'Mon Sep 06 2021 17:00:00 GMT+0200 (Central European Summer Time)'
Type: 'Recurring' -- Summary: '1:1 DR-MH' -- Start: 'Fri Feb 18 2022
15:05:00 GMT+0100' -- End: 'Fri Feb 18 2022 15:55:00 GMT+0100' --
TimezoneOffset: 'Fri Dec 10 2021 15
:55:00 GMT+0100 (Central European Standard Time)'
Skipping
'040000008200E00074C5B7101A82E0080000000070A925254DE8D70100000000000000001000000030BD25F133EB9B4596D9E5E4BB49CF28'
@  2022-03-04T14:05:00.000Z ( 2022-03-04T14:05
:00.000Z { tz: 'W. Europe Standard Time' } ) because it exists in exdate by
date lookup key
Type: 'Recurring' -- Summary: '1:1 DR-MH' -- Start: 'Fri Mar 18 2022
15:05:00 GMT+0100' -- End: 'Fri Mar 18 2022 15:55:00 GMT+0100' --
TimezoneOffset: 'Fri Dec 10 2021 15
:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: '1:1 DR-MH' -- Start: 'Fri Apr 01 2022
15:05:00 GMT+0200' -- End: 'Fri Apr 01 2022 15:55:00 GMT+0200' --
TimezoneOffset: 'Fri Dec 10 2021 15
:55:00 GMT+0100 (Central European Standard Time)'
Skipping
'040000008200E00074C5B7101A82E008000000006007D43C92FDD701000000000000000010000000516C0C48263D224DAE56B46D90C11595'
@  2022-02-07T13:00:00.000Z ( 2022-02-07T13:00
:00.000Z { tz: 'W. Europe Standard Time' } ) because it exists in exdate by
date lookup key
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Feb 14
2022 14:00:00 GMT+0100' -- End: 'Mon Feb 14 2022 14:55:00 GMT+0100' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Feb 21
2022 14:00:00 GMT+0100' -- End: 'Mon Feb 21 2022 14:55:00 GMT+0100' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Feb 28
2022 14:00:00 GMT+0100' -- End: 'Mon Feb 28 2022 14:55:00 GMT+0100' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Mar 07
2022 14:00:00 GMT+0100' -- End: 'Mon Mar 07 2022 14:55:00 GMT+0100' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Mar 14
2022 14:00:00 GMT+0100' -- End: 'Mon Mar 14 2022 14:55:00 GMT+0100' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Mar 21
2022 14:00:00 GMT+0100' -- End: 'Mon Mar 21 2022 14:55:00 GMT+0100' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Mar 28
2022 14:00:00 GMT+0200' -- End: 'Mon Mar 28 2022 14:55:00 GMT+0200' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'EMEA North Team call' -- Start: 'Mon Apr 04
2022 14:00:00 GMT+0200' -- End: 'Mon Apr 04 2022 14:55:00 GMT+0200' --
TimezoneOffset: 'Mon Jan
 03 2022 14:55:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Neurons Ninja Squad -FY22' -- Start: 'Sun
Apr 03 2022 18:00:00 GMT+0200' -- End: 'Sun Apr 03 2022 19:00:00 GMT+0200'
-- TimezoneOffset: 'Th
u Feb 03 2022 18:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'EMEA Day 1 Sales Huddle' -- Start: 'Mon Feb 07
2022 12:30:00 GMT+0100' -- End: 'Mon Feb 07 2022 21:00:00 GMT+0100' --
TimezoneOffset: 'Mon Fe
b 07 2022 21:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'EMEA Day 2 Sales Huddle' -- Start: 'Tue Feb 08
2022 13:00:00 GMT+0100' -- End: 'Tue Feb 08 2022 21:00:00 GMT+0100' --
TimezoneOffset: 'Tue Fe
b 08 2022 21:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Dennis: Bluewater Analyse' -- Start: 'Wed Feb
09 2022 09:00:00 GMT+0100' -- End: 'Wed Feb 09 2022 17:00:00 GMT+0100' --
TimezoneOffset: 'Wed
Feb 09 2022 17:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Dennis: Bluewater Analyse' -- Start: 'Thu Feb
10 2022 09:00:00 GMT+0100' -- End: 'Thu Feb 10 2022 17:00:00 GMT+0100' --
TimezoneOffset: 'Thu
Feb 10 2022 17:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'SE All Hands - International - (Wrap 21 & Kick
Off 2022)' -- Start: 'Thu Feb 10 2022 09:00:00 GMT+0100' -- End: 'Thu Feb
10 2022 10:00:00 GMT
+0100' -- TimezoneOffset: 'Thu Feb 10 2022 10:00:00 GMT+0100 (Central
European Standard Time)'
Type: 'Regular' -- Summary: 'Ivanti Trial / Eval / NFR license request' --
Start: 'Thu Feb 10 2022 14:15:00 GMT+0100' -- End: 'Thu Feb 10 2022
14:45:00 GMT+0100' -- Timez
oneOffset: 'Thu Feb 10 2022 14:45:00 GMT+0100 (Central European Standard
Time)'
Type: 'Regular' -- Summary: 'Dennis: Bluewater Analyse' -- Start: 'Fri Feb
11 2022 09:30:00 GMT+0100' -- End: 'Fri Feb 11 2022 17:00:00 GMT+0100' --
TimezoneOffset: 'Fri
Feb 11 2022 17:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Resultaten Bluewater' -- Start: 'Tue Feb 15
2022 09:30:00 GMT+0100' -- End: 'Tue Feb 15 2022 10:00:00 GMT+0100' --
TimezoneOffset: 'Tue Feb 1
5 2022 10:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Placeholder NRB demo' -- Start: 'Tue Feb 15
2022 13:00:00 GMT+0100' -- End: 'Tue Feb 15 2022 17:00:00 GMT+0100' --
TimezoneOffset: 'Tue Feb 1
5 2022 17:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Ivanti Global All Hands Call' -- Start: 'Thu
Feb 17 2022 17:00:00 GMT+0100' -- End: 'Thu Feb 17 2022 18:30:00 GMT+0100'
-- TimezoneOffset: 'T
hu Feb 17 2022 18:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Recurring' -- Summary: 'Tier 2: Xtraction 2022.1 Release Readiness '
-- Start: 'Mon Feb 21 2022 17:30:00 GMT+0100' -- End: 'Mon Feb 21 2022
18:00:00 GMT+0100' -- T
imezoneOffset: 'Mon Feb 21 2022 17:00:00 GMT+0100 (Central European
Standard Time)'
Type: 'Recurring' -- Summary: 'Tier 2: Xtraction 2022.1 Release Readiness '
-- Start: 'Mon Mar 14 2022 17:30:00 GMT+0100' -- End: 'Mon Mar 14 2022
18:00:00 GMT+0100' -- T
imezoneOffset: 'Mon Feb 21 2022 17:00:00 GMT+0100 (Central European
Standard Time)'
Type: 'Regular' -- Summary: 'Dennis: prep' -- Start: 'Thu Mar 03 2022
09:30:00 GMT+0100' -- End: 'Thu Mar 03 2022 10:00:00 GMT+0100' --
TimezoneOffset: 'Thu Mar 03 2022 1
0:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Demo Ivanti Service Management - Eleos' --
Start: 'Thu Mar 03 2022 10:00:00 GMT+0100' -- End: 'Thu Mar 03 2022
12:00:00 GMT+0100' -- Timezone
Offset: 'Thu Mar 03 2022 12:00:00 GMT+0100 (Central European Standard
Time)'
Type: 'Regular' -- Summary: 'Dennis: uitloop' -- Start: 'Thu Mar 03 2022
12:00:00 GMT+0100' -- End: 'Thu Mar 03 2022 12:30:00 GMT+0100' --
TimezoneOffset: 'Thu Mar 03 202
2 12:30:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Pilot Evaluation Rensa - Ivanti' -- Start:
'Wed Mar 09 2022 14:00:00 GMT+0100' -- End: 'Wed Mar 09 2022 15:00:00
GMT+0100' -- TimezoneOffset:
 'Wed Mar 09 2022 15:00:00 GMT+0100 (Central European Standard Time)'
Type: 'Regular' -- Summary: 'Ivanti Global All Hands' -- Start: 'Thu Mar 17
2022 16:00:00 GMT+0100' -- End: 'Thu Mar 17 2022 17:30:00 GMT+0100' --
TimezoneOffset: 'Thu Ma
r 17 2022 17:30:00 GMT+0100 (Central European Standard Time)'
get-active-events: Recurrances: 66 -- Regulars: 15
getEvents: Events for calendar 'Default' found. Event count: 81,

Total calendar events: 81
Spent '7.102' seconds to retrieve calendars

PS C:\temp\calendar-homey-test-master>

**Comment by DJranty** [comment]
Okay, so the app ran correctly now, I did remove some cancelled events
yesterday, so has to be one of those then. I am sorry to have bothered you
so much. I did learn a lot now how to trouble shoot this ical app. I really
rely on it with the flows I use, very useful to me.

Thanks again!

**Comment by runely** [comment]
No worries. Glad you got it fixed!
