### ISSUE TITLE
Feature: IF subject contains a search string? 

### ISSUE THREAD

**Issue by anderhau2** [runely/calendar-homey#286]
Great app! But Is it possible to have a WHEN card "subject contains" and input text? Then one could make flows to react on the Word "holiday" and keep office from being fired up, or change home/away rules.

Also, I could add an appointment for an evening and write "workshop", and it would tell homey to heat up workshop in time for my evening hobby work.

Today a Flow has to be made to react on a specific appointment, not a appointment with a spesific name or Word.

**Comment by runely** [comment]
This is already possible by using one of IcalCalendar's triggers in the **WHEN** section and using a *Logic card* in the **AND** section specifying the `Title` tag (or any of the other tags) from the trigger and checking it against a text of your choice.

This is how I automate activating vacation mode in my Homey:
https://homey.app/f/zfVM5X/

**Comment by anderhau2** [comment]
Beklager, men jeg glemte å svare deg. Å bruke trigger-tilhørende variabler som kriterier på den måten hadde jeg ikke tenkt på, og det endrer faktisk hvordan jeg tenker programmering av flows i Homey i mange andre sammenhenger også! Tusen takk!! 🙂👍

**Comment by anderhau2** [comment]
Funker fint med min vanlige kalender som jeg bruker til alt. Men siden avtalene ikke kan være private (da ser ikke appen emnet) så lagde jeg en egen ny kalender jeg har kalt "Smarthus". Tenker å styre mye nattsenking osv derfra. Bruker Outlook mot Office365.

Opprettet deling som på den andre, linken er helt lik bortsett fra noen forskjellige tall i ID"en, og slutter med en ICS-fil. Men på den får jeg feilmelding:

![Screenshot_20220214-233911_Homey](https://user-images.githubusercontent.com/97007825/153959046-c34c18fd-da39-4afd-9b10-f6219f77116a.jpg)

Tips?

**Comment by anderhau2** [comment]
Fant ut av det. Jeg hadde opprettet den ekstra kalenderen fra outlook.office.com. Den så helt strålende ut både på web, telefon og i Outlook på PC'en. Jeg lastet ned ICS-filene til både std kalenderen min og denne ekstra kalenderen. Åpnet de i notepad og da var det litt forskjell på timezone. Se under.

Opprettet på outlook.office.com:
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Smarthus
BEGIN:VTIMEZONE
TZID:Customized Time Zone
BEGIN:STANDARD
DTSTART:16010101T030000

Opprettet i Outlook:
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Kalender
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000

Jeg slettet den ekstra kalenderen og opprettet en ny fra Outlook, da var timezone på den også "Europe Standard Time", og den ble lest rett inn av appen din.

Om ikke du vil bruke tid på å tilpasse appen, så kanskje legge det til i en knowledge base? :-)

**Comment by runely** [comment]
Appen bruker et bibliotek som gjør selve konverteringen, så en eventuell endring må i såfall implementeres av utvikleren av biblioteket.

Takk for tilbakemelding. Jeg skal ta en kikk på det.

**Comment by anderhau2** [comment]
Mulig bug med repeterende avtaler. Jeg har en nattsenking på stuen som går "uendelig". På lørdag kveld ble vi sittende litt utover så jeg endrer akkurat lørdags kvelden til 01:00 i stedet for 12:00. Men nå har da calendar appen fått det for seg at alle disse avtalene fremover er fra 01:00. 

Fra Outlook:
![image](https://user-images.githubusercontent.com/97007825/154870520-d7285749-1f4a-4d65-87bd-0bb534a7ee6d.png)

Fra Homey:
![image](https://user-images.githubusercontent.com/97007825/154870608-cb734e8a-adf0-4140-bd02-30706884642f.png)

Tips?

**Comment by runely** [comment]
Fint om du oppretter en ny issue på dette
