### ISSUE TITLE
Bug: Reapeating appointment possibly misread by app after one instance has been changed

### ISSUE THREAD

**Issue by anderhau2** [runely/calendar-homey#290]
**Describe the bug**
I have a repeating appointment for lowering temperature at night time from 00:00 to 06:30. Last Saturday we were sitting up late and I changed only that instance of the appointment to 01:00-06:30.

Despite the appointment forward in time look correct in Outlook, the Calendar Homey app think all future instances of the appointment is changed.

Here is how it looks in Outlook:
![154870520-d7285749-1f4a-4d65-87bd-0bb534a7ee6d](https://user-images.githubusercontent.com/97007825/155220934-bced02c3-98b0-445c-9410-6bf4caaa4f07.png)

Here is how it looks if I make a new flow and have Homey list all upcoming appointments:
![154870608-cb734e8a-adf0-4140-bd02-30706884642f](https://user-images.githubusercontent.com/97007825/155221048-a06bc6e9-374a-4dfa-8484-f000299af7fc.png)

**Homey:**

 - Firmware: homeyVersion | "7.2.1"
 - IcalCalendar version: Current published version. Dont know where to find it.

**Comment by anderhau2** [comment]
A small added info. I changed only one instance of the appointment called "Stue Senking Helg", but as you see in the above screenshots the app misread also the other, unchanged, appointment called "Stue Senking Natt Ukedager".

Two days ago I changed the appointments from being from 00:00 -> 06:30 to 00:00 to 06:40, just to make it updated and see if the app reads the appointment again and fixes the problem. In Homey the appointment changed to 01:00 -> 06:40.

So I changed it again to 00:01 -> 06:31 and then finally it was read correctly and updated on Homey.

I will try to once again change ONE instance of the repeating appointment and see if it gets updated correctly, and report back. Mabe it's related to the starting time being 00:00?

**Comment by runely** [comment]
Thanks for the extra info, it made it easier to find the bug!

You are partially right, this happend because the start time was set to 00:00 and because the event were changed to not follow the recurrence rule. And since the start time was 00:00 the UTC time for this will be one hour earlier, making it 19.02 23:00. And the bug here was that i hadn’t taken that into account.

I have managed to recreate this on my calendar and has released a new test version where this is fixed.

Can you test it and let me know how it goes? https://homey.app/no-no/app/no.runely.calendar/IcalCalendar/test/

**Comment by runely** [comment]
Still there’s the bug where events set to start at 00:00 will be misread to 01:00. This seems to only affect events set to start at 00:00. And it seems to be because the start time is set as UTC 00:00 which makes it to be read as 00:00 + 1 (since Norway is GMT+1)

I'll look into this some more...

**Comment by anderhau2** [comment]
As mentioned above i tried to move starting point for one instance of the appointments, after I changed it to start 00:01. Now it works fine. 

Now it reads it like this:
![image](https://user-images.githubusercontent.com/97007825/155818610-95fa20d3-4dde-4f65-b0e3-51a7e89758f3.png)

I have highlighted the changed instance. This time it did not mess up the OTHER appointment either. Strange thing it read both appointments as changed to 01:00 even when the "ukedager" appointment was not the one I changed one instance in.

As long as I know to not use exactly 00:00, it's no problem for me...:-) I can work around it.

**Comment by runely** [comment]
Thanks for the thorough test 👍

**Comment by runely** [comment]
I have released a new test version which should fix misread recurring events starting at 00:00.

Could you test this aswell? https://homey.app/no-no/app/no.runely.calendar/IcalCalendar/test/

**Comment by runely** [comment]
According to my tests, this is now fixed in the new release `0.14.2`
