### ISSUE TITLE
Bug: Error in settings since version 0.14.2 

### ISSUE THREAD

**Issue by corvdniet** [runely/calendar-homey#292]
**Describe the bug**
Since 0.14.2 there's an error message in settings: "Fout bij laden van .ics bestand(en): ### : Cannot read property '2021-11-01' of undefined
    where ### is de name of the calender

**Homey:**
 - Firmware: 7.3.0 
 - IcalCalendar version: 0.14.2 

**Additional context**
Never had any problems before

**Comment by runely** [comment]
To be able to debug this i need some info/data.

Can you do the following:
1. Force a calendar synchronization by running/starting a flow with the action `Sync calendars` in it
2. After a minute send a diagnostics rapport from the app overview
    - Choose **IcalCalendar** from the app overview -> _Gear icon_ in the upper right corner -> `Create diagnostics report`

**Comment by corvdniet** [comment]
Report send a minute ago. Missed the report id, sorry

**Comment by runely** [comment]
I believe i found the bug (at least i've fixed a bug ;) )

Could you test the new released test version and let me know how it goes?
https://homey.app/a/no.runely.calendar/test/

**Comment by corvdniet** [comment]
I checked the test version ... YES!!! That did the trick.
Thank you very much for your fast action
