### ISSUE TITLE
Apple calendar - Maximum number of redirects exceeded

### ISSUE THREAD

**Issue by ehdegroot** [runely/calendar-homey#296]
since last update, the app doesn’t work anymore.
syncing the apple calendars gives the error: Maximum number of redirects exceeded

what happened?

**Comment by runely** [comment]
This has nothing to do with my app. The problem lies with Apple.

I tried to visit my own Apple calendar URL in **Chrome**, **Safari** and **Firefox**, and they all show the same error:

![image](https://user-images.githubusercontent.com/25814673/156443329-5b4f5962-fd78-4f25-b2ca-4a257c7d12c9.png)

**Comment by ehdegroot** [comment]
oh oke… weird… well, thank you again!
