### ISSUE TITLE
Won't trigger on read only calender?

### ISSUE THREAD

**Issue by ThomasWi** [runely/calendar-homey#310]
**Describe the bug**
I have 7 different google calenders (all family) connected to the app and all except one will trigger on event like it supposed to do. The one that's not triggering I have only read permission to....is this why it won't work or what could it be?

**To Reproduce**
It doesn't make any real bug but it won't work like I expect.

**Expected behavior**
I expect notice being triggered like on my 4 other flows pointing thowards other calenders.

**Screenshots**

**Homey:**
 - Firmware: 7.3.0
 - IcalCalendar version: 0.15.0

**Additional context**

**Comment by runely** [comment]
There are two iCal addresses on a Gmail calendar. And if your calendar isn't made public you will have to use the privat iCal format address.

1. `The public address in iCal format` : To use this address in other applications than Gmail, the calendar has to be made public. (as stated on the settings page of the calendar in Google Calendar). **If the calendar is not public you will get a 404 error code**
2. `The privat address in iCal format` : Use this address to open the calendar in other applications without making it public

Which one are you using?

**Comment by ThomasWi** [comment]
Hi,

Thanks for the fast replay!

Oh, yes....that was the problem....the calendar wasn't public. I copied the
private address and it started working at once.

Thanks!

Regards
Thomas


Den sön 24 apr. 2022 kl 10:56 skrev Rune Moskvil Lyngås <
***@***.***>:
