### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by Willemss001** [runely/calendar-homey#313]
Dear,
since last update, all my calendar events are now starting 2 hours later then actually planned.
E.g. Event in calendar starts at 7am but iCal says 9am. Date and time of my Homey is ok.
Any idea how to fix this?

Thanks and kind regards,
Stefan

**Comment by runely** [comment]
Can you make sure you've installed version **1.0.4** and then perform these steps:

1. Make a new Flow where:
    - the trigger card is Flow → This flow is started
    - the action card is IcalCalendar → Sync calendars
1. Run the created flow
1. Wait for 3 minutes
1. Send me a diagnostics report by doing the following:
1. Go to More → Settings in your Homey app on your phone
    1. Choose Apps
    1. Choose IcalCalendar
    1. Click the gear icon in the upper right corner
    1. Click Create diagnostics report

**Comment by Willemss001** [comment]
Hi Runely,

Hope you're well.

Done..bdd56fdd-4a56-412e-89c3-df164f5ddcdc.

Many thanks in advance!

Kr

**Comment by runely** [comment]
Hi there.

I've done some digging and your calendar is using a customized (non standard) timezone for your events (`Customized Time Zone`). This is an Exchange thing. A wild guess, have you setup corrrect timezone in your Exchange account? https://support.microsoft.com/en-us/office/change-the-time-zone-and-language-settings-in-outlook-on-the-web-65239869-12e7-4a9d-bca1-76b0ad7ce273

**Comment by Willemss001** [comment]
Hello there and thanks for support!

I had a quick look at the time zone settings of the mailbox/calendar but that looks fine to me. UTC+1..[image0.jpeg]

Anything else you want me to check?

Thanks,
Stefan

Op 7 mei 2022 om 21:40 heeft Rune Moskvil Lyngås ***@***.***> het volgende geschreven:

﻿

Hi there.

I've done some digging and your calendar is using a customized (non standard) timezone for your events (Customized Time Zone). This is an Exchange thing. A wild guess, have you setup corrrect timezone in your Exchange account? https://support.microsoft.com/en-us/office/change-the-time-zone-and-language-settings-in-outlook-on-the-web-65239869-12e7-4a9d-bca1-76b0ad7ce273

**Comment by runely** [comment]
I'm not sure why **Exchange** / **Live** use `Customized Time Zone` instead of your correct timezone..

However, the latest version `1.0.6` should take this into account.

Please install `1.0.6` and let me know how it turns out

**Comment by Willemss001** [comment]
That latest version did the job!
Thanks a lot for your help and keep up the good work!

Best regards,
Stefan

Op 11 mei 2022 om 09:13 heeft Rune Moskvil Lyngås ***@***.***> het volgende geschreven:

﻿

I'm not sure why Exchange / Live use Customized Time Zone instead of your correct timezone..

However, the latest version 1.0.6 should take this into account.

Please install 1.0.6 and let me know how it turns out
