### ISSUE TITLE
Req: output on error

### ISSUE THREAD

**Issue by Tiwas** [runely/calendar-homey#316]
First of all - thanks for fixing the error when reading the ics.

That makes me believe it would be nice to have some sort of "on error" handler.

Would it be possible to get a flow card for catching errors? Like:
When: error reading ics
What: <some action> #error

This might be one of the most useful apps to date 😎

**Comment by runely** [comment]
Thanks for the suggestion!

Errors from reading the `.ics` file is visible in the bottom of the settings page. But a trigger card for these errors would be much better 👍

**Comment by runely** [comment]
This is implemented in the next release, `1.1.0`
