### ISSUE TITLE
Feature: An event starts in X minutes in Y calendar

### ISSUE THREAD

**Issue by GrimSQL** [runely/calendar-homey#330]
**Is your feature request related to a problem? Please describe.**
I have two different calendars, and they don't work together independently to each other, not that I know of.

**Describe the solution you'd like**
The flow card: "An event starts in X minutes" already exsist and is great! However, it would be amazing if it could include "An event starts in X minutes AND in Y calendar" since I have a two different calendars I want to start different flows from. 

**Describe alternatives you've considered**
A new flow card in the WHEN section labeled  "An event starts in X minutes AND in Y calendar"

**Comment by runely** [comment]
This is already possible by using the trigger **An event starts in X minutes** and in the _AND_ section use a **logic** card to check if the _Calendar name_ tag from the trigger card is equal to the calendar name you are interested in.

**Comment by GrimSQL** [comment]
Thank you for the very quick reply! I'll give it a try.

**Comment by runely** [comment]
Did this solve your request?

**Comment by GrimSQL** [comment]
Yes this works perfectly, thank you again!
