### ISSUE TITLE
Feature: Avtale som inneholder ""Søkeverdi"" i kalender ""Velg kalender"  "pågår"

### ISSUE THREAD

**Issue by haakaak** [runely/calendar-homey#341]
Hello 
Nice APP 
Lurte på det var planer om et kort som viser i punkt 2. Eller det mulighet for få det.

"OG- kort" 
1. Avtale som inneholder ""Søkeverdi"" for avtalen i kalender ""Velg kalender"" starter inne "Antall"   "...."

Er det mulighet for et "OG-kort" som har denne funksjonen:
2. Avtale som inneholder ""Søkeverdi"" i kalender ""Velg kalender"  "pågår"

Tanken bak dette er for slippe legge inn spesifikke avtalen pågår, men at du kan basere deg på "Søkeverdi"

**Comment by runely** [comment]
Jeg har ikke hatt noen planer for det, men et *OG-kort* for **Avtale som inneholder *Søkeverdi* i kalender *Velg kalender* pågår** kan legges til

**Comment by runely** [comment]
Et OG-kort `Avtale som inneholder søkeverdi i valgt kalender pågår` er lagt til i versjon **1.4.0**. Versjonen er i test frem til den godkjennes av Homey. Testversjonen kan testes her: https://homey.app/a/no.runely.calendar/test/

**Comment by haakaak** [comment]
Fantastisk, da skal eg teste denne ut. Takk

**Comment by runely** [comment]
Versjon 1.4.0 er lansert i app store.

Closer denne issuen. Skulle det være noe feil du ser med denne conditionen, skriv en kommentar her så gjenåpnes saken.
