### ISSUE TITLE
Homey app gives constant error: No network available

### ISSUE THREAD

**Issue by nouvellemaison** [runely/calendar-homey#345]
Reinstalled the app. Using outlook on windows PC. Made a new link to ics file. Also tried this with Iphone. Imported in ical app on homey. Constantly network request failed. The app had worked until a couple of days ago. I also see the message that the flow has been disabled due to a start 60 times. Never seen this before. Can you help with this?

**Comment by nouvellemaison** [comment]
It works again!  Do not know what was wrong!

**Comment by runely** [comment]
Sounds like there were some network issues at your end or at your calendar/mail hosting provider.
