### ISSUE TITLE
Create event? Am I missing something?

### ISSUE THREAD

**Issue by dooniem** [runely/calendar-homey#355]
Hi. I can’t seem to understand whether or not this app can create events in a calendar? Maybe it seems weird to create events from Homey for some, I don’t know, but since the release of advanced flows and homeyscript, I have some ideas for calendar events Homey can auto-create, but instead of homeyscripting the whole “create event” I thought this app could help a newbie out?

**Comment by runely** [comment]
Creating events on a calendar requires the use of calendar provider specific API's along with auth handling. That was and is not the purpose of this app. This app is for **_reading_** public calendars only.
