### ISSUE TITLE
Avtale som innholder ... i kalender.... slutter innen...

### ISSUE THREAD

**Issue by haakaak** [runely/calendar-homey#359]
Hei igjen

Er det mulighet for sette opp ett ønske om ett "og" kort som dette.
"Avtale som innholder... i kalender ... slutter innen...."

Hilsen 

Håkon Hansen

**Comment by runely** [comment]
Kortet er lagt til og ny versjon ligger til Review hos Athom. Prøv gjerne ut testversjonen herfra og si ifra om det er noe feil: https://homey.app/no-no/app/no.runely.calendar/IcalCalendar/test/

**Comment by haakaak** [comment]
Takk igjen


Da skal eg prøve det ut

lør. 24. sep. 2022 kl. 10:59 skrev Rune Moskvil Lyngås <
***@***.***>:
