### ISSUE TITLE
An event today

### ISSUE THREAD

**Issue by liams239** [runely/calendar-homey#36]
Hi,

Is it possible to add a flow card that you can activate a flow when there is an (specific) event today? Now it needs to start or to start within the hour. But what I want to do is: When there is a event/Task in the afternoon you can activate in the morning a flow for example a reminder to something. For example: If you work in shifts and you have a evening shift it reminds you to charge your bike in the morning.

Is this possible to add such a thing?

Many thanks for this great app.
Kind regards,

Liam

**Comment by runely** [comment]
Thanks for the feedback.

I chose not to add a trigger for a specific event because you can combine the "Event starts" trigger with the "Event is ongoing" condition where you can choose a specific event. This will do what you want 🙂

**Comment by liams239** [comment]
Hi,

I think i'm missing the right settings then. I can indeed set Event starts or Event Starts in... but then I just can choose for maximum 60 min in front. 

How do I configure it when I want the follow thing?: I want to set a reminder at 08:30 when my shifts starts in the afternoon at 15:00. Now I have set a flow that he reminds me every morning when I"m still at home. But there are days i'm not at work, so I want just that reminder on the days that I have a "late shift".

other example where I want to use it for: When I have an early shift (starts at 06:30) I want that he Activate my alarm from homey for the next day. So Homey now that he needs to activate a alarm flow so the bathroom is warm, it wakes me on time,... . (He needs to check my calendar every evening at for example 20:00 so he nows to activate or deactivate my alarm).


Thanks for the help!

**Comment by runely** [comment]
I'm sorry, I misunderstood 😕

If you want a flow to trigger at 08:30 but only when there’s a calendar event today with the title "late shift", you can do:
1. In the When section add the "Clock is" and set it to 08:30
1. In the And section add Logic -> "Tag contains".
    1. For the tag, select "Todays events, title and time"
    1. For the text, input "late shift"

Here’s an example (Tag name might be in Norwegian): https://homey.app/f/-YaHpd

**Comment by liams239** [comment]
Hi,

Sorry for the late reply. I forgot the tags, It works good for this. Thanks.

I don't get it to work for a next day event with for example "early shift". (Example like above: When I have an early shift (starts at 06:30) I want that he Activate my alarm from homey for the next day. So Homey now that he needs to activate a alarm flow so the bathroom is warm, it wakes me on time,... . (He needs to check my calendar every evening at for example 20:00 so he nows to activate or deactivate my alarm).

Is it possbile with any tag, or card?

And again already thanks for the help.

**Comment by runely** [comment]
I'm not completely sure i understand what you're asking, but if you want a flow to check your calendar at 20:00, use the "Clock is" as above and set it to 20:00. And if you only want to activate your alarm if your next event is "early shift", then in the And section use the Logic as above and for the tag choose "Next event" and for the text input "early shift".

If "early shift" is not your next event in your calendar this will not work.

Hope it helps 👍

**Comment by liams239** [comment]
Correct, my question was indeed what if you next event is not your early shift. If there was a tag like "Tomorrow events, title and time" like the one for today it is possible i think. If it's possible to integrate when you add new features in the app it would be great. (But without is is still a great app of course 😁 )

But my questions are now indeed answered. I know now that it is possible when it's your next event. 

Many thanks for the help and solutions! 

Best regards,
Liam

**Comment by runely** [comment]
I will look into a tomorrow events tag
