### ISSUE TITLE
App crash when adding ical link

### ISSUE THREAD

**Issue by otteminat0r** [runely/calendar-homey#375]
Hi

I am unable to add Google ical link.
App crashes instantly with timeout error.

Only way to try new configuration is to Uninstaller, install and try again.. same error though 😕 

Here is the bug report.  If it works.
a2eca951-7e3a-49ed-988e-b664456e35cc

Tnx :)

**Comment by runely** [comment]
There is no problems in the diagnostics report you have sent. It shows you have added a google calendar named **Kriss** and it has successfully loaded 12 events..

I did however receive a crash report late last night, at 23:29. If it was from your Homey, then the calendar you had entered at that time had an event with an invalid `DateTime`. Unfortunately it did not tell me which event.

You can validate your ical here: https://icalendar.org/validator.html

**Comment by otteminat0r** [comment]
Thank you.

Seems like there was allot of problems "back in time" .. i cleaned the
calendar tnx to the help of the validator tool.
now it workes :)

-Kristoffer
