### ISSUE TITLE
Feature: VCS support?

### ISSUE THREAD

**Issue by Ranney1** [runely/calendar-homey#377]
**Is your feature request related to a problem? Please describe.**
For our work (hospital), we have a unregular schedule. Our hospital send every employee a vcs calendar link to get all the shifts automatically in the personal calendar. It would be great if I can use this feed to learn homey when we I'm at work!

**Describe the solution you'd like**
At this moment, I get all my shifts automatically in my calendar. For now, I make a new (manual) event for every shift in a google calendar that is supporting 'ical'. It is great if homey supports the vcs feed directly!

**Describe alternatives you've considered**
There is no other app with vcs support. So just make manual new items in another calendar that supports iCal is an alternative. 

**Additional context**
Technical info feed:
BEGIN:VCALENDAR
VERSION:2.0

**Comment by runely** [comment]
**vcs** is the predecessor of **ics**. The v1 of **ics** if you'd like. After a quick google search it seems that people are encouraging to use **ics** if possible.

So for this small project i don't think that would be beneficial for a lot of users.

There does seem to be a number of converters out there from **vcs** to **ics**. Maybe you can use one of those to automatically convert it to **ics** format and insert them into your google calendar.

**Comment by runely** [comment]
Also, it would seem strange if your calendar provider doesn't support **ics** export/sharing possibilities

**Comment by Ranney1** [comment]
Many thanks for your response and help! If that is the case, than it is me and I will take the time every week to type them over!
The application that the hospital use (they use it in more hospitals) is giving me the personal url. In the application, they call it the 'iCal' link. But it is not working when I enter it in the homey app. It is working on IOS. When I open the link in Safari, i see a long page with info. Starting with the info:

BEGIN:VCALENDAR
VERSION:2.0

So I think that it is indeed an older standard.

Many thanks for your time and help!

**Comment by Ranney1** [comment]
Maybe good to say, the sheddule of an nurse is irregular. So it cannot be imported. It will be released every month but also changed every day. So the feed is updating every 10 minutes.

**Comment by runely** [comment]
> Many thanks for your response and help! If that is the case, than it is me and I will take the time every week to type them over!
> The application that the hospital use (they use it in more hospitals) is giving me the personal url. In the application, they call it the 'iCal' link. But it is not working when I enter it in the homey app. It is working on IOS. When I open the link in Safari, i see a long page with info. Starting with the info:
> 
> BEGIN:VCALENDAR
> VERSION:2.0
> 
> So I think that it is indeed an older standard.
> 
> Many thanks for your time and help!

**ics** files do start with `BEGIN:VCALENDAR` and `VERSION:2.0` so it might be an ice file 🤔

If you could open the file in safari, copy all the text and keep some events in there (I don't need all) and (obviously) replace any private info, and paste it here I can see if there is anything I can figure out!

**Comment by runely** [comment]
Closing this issue for now because the lack of data. Please feel free to comment here again if you manage to get the ics content.
