### ISSUE TITLE
Summertime / Wintertime

### ISSUE THREAD

**Issue by heronimus68** [runely/calendar-homey#379]
**Is your feature request related to a problem? Please describe.**
I have a repeating appointment, every week on Wednesday at 10:00 AM. I think it was created at summertime (DST). The triggercard "An appointment starts in 2 hours" triggers 3 hours before when Homey is in Wintertime (DST off)

**Describe the solution you'd like**
Don't know if this is a bug or a behavior in Calendar import. I don't know what solution is possible here, DST independence?

**Describe alternatives you've considered**
Make a repeating appoint for max. half year according to the DST change.

**Additional context**
{none}

**Comment by runely** [comment]
Hmm.. Could you send me a diagnostics report from the app -> settings (gear icon) screen?

**Comment by heronimus68** [comment]
hivr Rune,

diagnostic report sent to you.  code: 669927b3-2438-4275-9f20-b167f8fd5bf8

Best regards, Jeroen

**Comment by runely** [comment]
I don't see any problems in the diagnostics report. Could you open your calendar url (ics file) in a text editor, find the event you are having trouble with, and paste it here?

**Comment by heronimus68** [comment]
I try to
