### ISSUE TITLE
Bug: 2 week long events

### ISSUE THREAD

**Issue by late4marshmellow** [runely/calendar-homey#380]
**Describe the bug**
The "and" card do not read ongoing events that last 2 weeks, it does read it on the day event starts and the events that will happend in the future (this particular event is set repetetive every 4 weeks)

**To Reproduce**
And card: Event containing ... calendar ... is ongoing

**Expected behavior**
I use this to define if my kid whos living with me for two weeks every two week is home. 
This way i can automaticcaly switch off the heating/lighs in my kids room, during night/day and when away/home.

**Screenshots**
![image](https://user-images.githubusercontent.com/79985161/202893469-a15bd0c9-5d92-481f-9cb2-4ddacff5cd4b.jpeg)

![image](https://user-images.githubusercontent.com/79985161/202893480-02e40552-78ad-4e47-accd-d8f7f4c3ab7e.jpeg)
**Homey:**
 - Firmware: 8.0.8
 - IcalCalendar version: 1.8.1

**Additional context**

**Comment by late4marshmellow** [comment]
Forgot to mention that the other "and" card in my screenshot is my workaround to define a logic yes/no card "if home"

Just added the failing card for visual description.

**Comment by runely** [comment]
Thanks for reporting this! I did manage to reproduce this and fix it! Version `1.8.2` released. Let me know how it goes

**Comment by late4marshmellow** [comment]
Great! Now it works. thank you so much 😊
