### ISSUE TITLE
'read ECONNRESET' error

### ISSUE THREAD

**Issue by Ranney1** [runely/calendar-homey#385]
**Describe the bug**
Both of my google calendar (secret link) from 2 different user account are not working. Both of them give the 'read ECONNRESET' error in the Homey ICAL app.

**To Reproduce**
1. go to the Homey ical app
2. click config
3. scroll to the bottom of the page
4. Here is the error. 

Whatever I do (removing and re-adding, replacing it for a nor generated link, etc., I get the error back in some minutes. all the labels in the already existing flows are not available and 'grey'. 

**Expected behavior**
More information on what the problem is. The link is working on other apps and when opening in 'safari' all the iCAL info is there. So this beautiful app working again would be great!

**Screenshots**
![IMG_7777](https://user-images.githubusercontent.com/70540060/205243127-dad38121-bc12-4eea-9997-92790333057d.PNG)
**Homey:**
 - Firmware: 8.1.0
 - IcalCalendar version: 1.8.2

**Comment by Ranney1** [comment]
Just did a complete reinstall of the app. All Google calendar iCal links give me this error (secret Google calendar link). This was working until some weeks ago. In all other apps the iCal file/link is working fine.

**Comment by Ranney1** [comment]
After long troubleshooting:
-Removing en re-adding the iCal link => nothing changed
-generating new iCal link => nothing changed
-Reinstalling the app => nothing changed
-Rebooting homey => it is working again.

**Comment by runely** [comment]
That did sound like an issue on your end (Homey)

ECONNRESET means that the server unexpectedly closed the connection.

Good troubleshooting fixed it 👍
