### ISSUE TITLE
Timezone seems mishandled

### ISSUE THREAD

**Issue by Zikki1981** [runely/calendar-homey#391]
**Describe the bug**
My system connects to an ICS generated by familywall. All the devices and apps are configured to TZ Europe\Brussels. 
any event popping in the app accordingly to the timezone.

However, when retrieved into Homey (which is setup on the same timezone) all time are 1 hour later than they should be (an event starting at 10 local time is popping into Homey as starting at 11.

**To Reproduce**
1. Go to Calendar app
2. Click on Create a new meeting
3. Save
4. Launch a sync flow to get the updated ical
5. start a flow manually displaying the new event with a notification in the log mentionin start time
6. see the hour difference

**Expected behavior**
starting time aligned as all systems are in the same timezone. The same Ical imported in any calendar app is at the correct time

**Screenshots**

**Homey:**
 - Firmware: 8.1.0
 - IcalCalendar version: 1.8.3

**Additional context**

**Comment by runely** [comment]
So the calendar you are importing into IcalCalendar is generated and hosted from FamilyWall?

If you import the calendar into your calendar app on your phone or pc, is the events presented correct there?

If so, could you trigger a calendar sync, wait a minute and then send a diagnostics report from the app's screen?

**Comment by kjeet90** [comment]
@runely I had the same experience yesterday. I have a calendar imported into my gmail and the trigger of the event was one hour late.
![image](https://user-images.githubusercontent.com/10712631/207788973-c821f191-ba7a-4d77-abc4-7291bb03ba9f.png)
![image](https://user-images.githubusercontent.com/10712631/207789014-51d2be06-3ef5-4f97-a06d-e38392dba13d.png)
![image](https://user-images.githubusercontent.com/10712631/207789169-0c265dc7-8fda-479b-b397-15dbf9084a28.png)

**Comment by runely** [comment]
I don't see any problems in the diagnostic reports you guys have sent.

I just released a new version where you can enable logging to console off all events, so a diagnostic report is more usefull.

Could you guys install `v1.9.0`, activate the `Log all events` from the settings screen, trigger a synchronization, and after a minute send a new diagnostics report?

**Comment by runely** [comment]
After some more digging, it seems like your calendar's are missing timezone information.

In these cases **IcalCalendar** uses the local timezone of your Homey.

I have added a fix for this, and I'm running this on my homey now to see if everything still works.

**NOTE**: Not using timezone, will probably give wrong time in summer time or winter time. I recommend to look into your calendars to see if timezones can be added

**Comment by kjeet90** [comment]
When I look in the calendar settings it seems like it has a timezone:
![image](https://user-images.githubusercontent.com/10712631/208360734-e25974f6-ae47-4076-aed4-3ac1140e10b4.png)

Just ran sync on v1.9.0 and this is the diagnostics report ID: 35a5da6f-e069-46fd-a56b-c3547cdcf918

**Comment by runely** [comment]
Could you please activate the **Log all events** from the _settings screen_ as well, trigger a synchronization, and after a minute send a new diagnostics report?

There wasn't any more logging in this diagnostics report than the last

**Comment by kjeet90** [comment]
It was enabled in the settings, tried to restarted the app, synced, waited a minute and sent a new report now: 8e5bbd4c-4eec-4bb9-ad49-3ca229095ddc

**Comment by runely** [comment]
I released a new test version, `v1.10.0`, which takes into account that an event might not have registered a timezone, aswell as log out the timezone used for each event.

Could you guys please install this test version, activate the `Log all events` from the settings screen, restart the app, and after a minute or two send a diagnostics report?

https://homey.app/no-no/app/no.runely.calendar/IcalCalendar/test/

**Comment by kjeet90** [comment]
Report ID from v1.10.0 a couple of minutes after restart: 6a081315-53df-4be7-afc4-13b54d11c270

**Comment by runely** [comment]
A reply is sent on your diagnostics report. I'm guessing it will be sent to the mail address you have registered in your homey account

**Comment by Zikki1981** [comment]
Sorry I was otherwise engaged. I received from familywall the information that the ical contains the timezone.

**Comment by runely** [comment]
I'm guessing your calendar provider is using the non-standard `X-WR-TIMEZONE` property to set timezone once for all events.. It's recommended **not** to use this property, and the library i'm using to parse calendars does **not** take this property into account either.

The recommended way, that 95% of all calendar providers use, is to add `VTIMEZONE` information and reference this timezone in each event that should use a timezone!

In `v1.10.0` the timezone from Homey is not used anymore if your event hasn't specifically set a timezone.
The lack of timezone in your events and this change in **IcalCalendar** might give some wrong timestamps in either winter time or summer time.

Your regular events do not have timezone set (i've masked the summary) as shown in the list below.

```text
[log] 2022-12-20 15:18:44 [IcalCalendar] Regular: Axxxxx Txxxxxxxx -- Moment<2023-01-28t10:00:00+00:00> -- Moment<2023-01-28t11:00:00+00:00> -- Sat, 28 Jan 2023 10:00:00 GMT -- TZ:missing/invalid
[log] 2022-12-20 15:18:44 [IcalCalendar] Regular: Bxxxxxx Bxxxxx -- Moment<2023-01-03t11:30:00+00:00> -- Moment<2023-01-03t13:30:00+00:00> -- Tue, 03 Jan 2023 11:30:00 GMT -- TZ:missing/invalid
[log] 2022-12-20 15:18:44 [IcalCalendar] Regular: Jxx Mxxxxx dx Nxxx Ixxx+ Dxxxx -- Moment<2022-12-22t15:00:00+00:00> -- Moment<2022-12-22t21:00:00+00:00> -- Thu, 22 Dec 2022 15:00:00 GMT -- TZ:missing/invalid
[log] 2022-12-20 15:18:44 [IcalCalendar] Regular: Jxx txxxx -- Moment<2022-12-21t15:00:00+00:00> -- Moment<2022-12-21t17:00:00+00:00> -- Wed, 21 Dec 2022 15:00:00 GMT -- TZ:missing/invalid
[log] 2022-12-20 15:18:44 [IcalCalendar] Regular: B-xxx Jxx rxxxx -- Moment<2023-01-07t12:00:00+00:00> -- Moment<2023-01-07t14:00:00+00:00> -- Sat, 07 Jan 2023 12:00:00 GMT -- TZ:missing/invalid
[log] 2022-12-20 15:18:44 [IcalCalendar] Regular: Bxxxxx mxxxx -- Moment<2023-01-01t12:00:00+00:00> -- Moment<2023-01-01t15:00:00+00:00> -- Sun, 01 Jan 2023 12:00:00 GMT -- TZ:missing/invalid
[log] 2022-12-20 15:18:44 [IcalCalendar] Recurring event: Dxxxxx Lxxxxx -- Moment<2023-01-15t14:00:00+00:00> -- Moment<2023-01-15t15:00:00+00:00> -- Sun, 15 Jan 2023 14:00:00 GMT -- TZ:missing/invalid
[log] 2022-12-20 15:18:44 [IcalCalendar] Regular: Axxx Jxx -- Moment<2022-12-23t15:00:00+00:00> -- Moment<2022-12-23t17:00:00+00:00> -- Fri, 23 Dec 2022 15:00:00 GMT -- TZ:missing/invalid
```

**Comment by Zikki1981** [comment]
Dear developer,So, little update, the information coming in homey are now correct but the trigger when an event is supposed to start is still at another timezoneExample : a flow getting the next event information is getting meeting X 4 pm... but the flow triggered by this very event will be triggered at 5pm...Envoyé à partir de Outlook pour Android

**Comment by runely** [comment]
Hi. This will be fixed in the next release, `v1.11.0`.

**Comment by runely** [comment]
`v1.11.0` is released

**Comment by Zikki1981** [comment]
Hi,Still the same issue.The second event is supposed to trigger 30 minutes before the event but it's here one hour late Envoyé à partir de Outlook pour AndroidDe : Rune Moskvil Lyngås ***@***.***>Envoyé : mercredi 28 décembre 2022, 12:43À : runely/calendar-homey ***@***.***>Cc : Gregoris ***@***.***>; Author ***@***.***>Objet : Re: [runely/calendar-homey] Timezone seems mishandled (Issue #391)Closed #391 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by runely** [comment]
Can you activate the `Log all events` from the settings screen, restart the app, and after a minute or two send a diagnostics report?

And also what's the name of the event which is starting an hour late?

**Comment by Zikki1981** [comment]
025bf9f4-b2e2-42d8-885b-83836e9e6e68Event has been detailed in the diagnosric reportEnvoyé à partir de Outlook pour Android

**Comment by runely** [comment]
The event you detailed in the diagnostics report is not loaded into **IcalCalendar**. To able to help you i need a diagnostics report which contain the event in question.

Please reproduce the problem with a new event that you are certain is loaded into **IcalCalendar** and then send a new diagnostics report following the same procedure as stated above

**Comment by Zikki1981** [comment]
328e60e6-ba43-4412-b634-46616737fb74It’s difficult to show you an untriggered event if the past events are not in the logs.I create a new one and the event is in the logs.You just have to assume that the trigger event will be an hour lateEnvoyé de mon iPhoneLe 29 déc. 2022 à 14:07, Rune Moskvil Lyngås ***@***.***> a écrit :﻿
The event you detailed in the diagnostics report is not loaded into IcalCalendar. To able to help you i need a diagnostics report which contain the event in question.
Please reproduce the problem with a new event that you are certain is loaded into IcalCalendar and then send a new diagnostics report following the same procedure as stated above

**Comment by runely** [comment]
The purpose of enabling `Log all events` is that **IcalCalendar** will log all events that are loaded in.

The event you mentioned in the diagnostics report is loaded in and hasn't happened yet at the time the diagnostics report was generated (18:14)!

The event is loaded into **IcalCalendar** like this:
```text
[log] 2023-01-02 18:13:57 [IcalCalendar] Regular: Test homey logs -- Moment<2023-01-02t18:55:00+00:00> -- Moment<2023-01-02t19:55:00+00:00> -- Mon, 02 Jan 2023 18:55:00 GMT -- TZ:missing/invalid -- event/9504592_185952984
```

Meaning, it `starts` @ *02.01.2023 18:55* and `ends` @ *02.01.2023 19:55*

**The calendar provider you are using does not set a timezone on the events. Hence, this article applies to you: [Timezone in your calendar](https://github.com/runely/calendar-homey#timezone-in-your-calendar-ics)**

**Comment by runely** [comment]
Some changes made in `1.11.3`. May fix something. Anyway, since calendars are missing timezone information on the events itself, this applies as stated earlier: [Timezone in your calendar](https://github.com/runely/calendar-homey#timezone-in-your-calendar-ics]
