### ISSUE TITLE
Feature request : support for busystatus

### ISSUE THREAD

**Issue by cyber-93** [runely/calendar-homey#394]
maybe I missed something if it is already implemented.
But I would like a AND card  to check the busy status of an event.
This a .ics example from outlook
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-BUSYSTATUS:WORKING ELSWHERE
X-MICROSOFT-CDO-BUSYSTATUS:OUT OF OFFICE

Greets Luuk 

“en”: “tentative”
“no”: “”
“nl”: ”voorlopig”
“de”: “”
“sv”: “”

“en”: “busy”
“no”: “”
“nl”: ”bezet”
“de”: “”
“sv”: “”

“en”: “free”
“no”: “”
“nl”: ”beschikbaar”
“de”: “”
“sv”: “”

“en”: “WORKING ELSWHERE”
“no”: “”
“nl”: ”werkt ergens anders”
“de”: “”
“sv”: “”

“en”: “out of office”
“no”: “”
“nl”: ”werkt ergens anders”
“de”: “”
“sv”: “”

**Comment by runely** [comment]
You are talking about two different things here.

Condition cards (AND cards) does not have tags, but they can use tags from the trigger card.

A `Status` tag isn't present on the trigger cards at the moment, but i'll add it in the next release. It will not be translated statuses as pr your suggestion, but it will show the actual status information on the calendar event.

**Comment by runely** [comment]
A `Status` tag has been added to the following triggers:

- **Event added**
- **Event starts**
- **Event starts in**
- **Event starts from calendar**
- **Event ends**
- **Event ends in**

The status is filled from **X-MICROSOFT-CDO-BUSYSTATUS** or **MICROSOFT-CDO-BUSYSTATUS**

Will be released in `v1.10.0`

**Comment by runely** [comment]
`v1.10.0` released

**Comment by cyber-93** [comment]
Thanks for the trouble. 
works great.

greets Luuk

**Comment by runely** [comment]
The `Status` for an event is also shown on the event list in these three AND cards:

- Specific event starts within...
- Specific event is ongoing
- Specific event ends within...

Example:
![image](https://user-images.githubusercontent.com/25814673/208976603-233992d6-2d41-41bf-b1f8-913de98bb8d2.jpeg)
