### ISSUE TITLE
deleted recurring events not deleted in homey

### ISSUE THREAD

**Issue by ronwell74** [runely/calendar-homey#401]
deleted recurring events still show up in homey, even after syncing

**Comment by runely** [comment]
Hi. I need some info to look into this. As previously stated I can't reproduce this with my own recurring events..

Please be sure that one of these deleted recurring events are present in the **IcalCalendar** app before doing the next steps:

1. Make sure you have installed the latest **IcalCalendar** app, `1.11.0`
1. Activate `Log all events` in the settings page
1. Restart the app
1. After two minutes, send a diagnostics report

**Comment by ronwell74** [comment]
here you go
34f77a1a-b651-4e28-828b-5ee765080757

**Comment by runely** [comment]
I found a bug in the logic for finding excluded dates. I have released a new version, `1.11.1`, which should fix this.

Can you please install it and let me know how it works out

**Comment by ronwell74** [comment]
will do

**Comment by runely** [comment]
FYI, you don't have to wait to the actual day of the event to see if this has fixed it.

You can see all synced in events by doing this: https://github.com/runely/calendar-homey#see-events-synced-in

If you don't see the deleted event there, its all good.

Or you can restart the app, wait two minutes and send me a new diagnostics report.

**Comment by ronwell74** [comment]
it worked thank you.
