### ISSUE TITLE
iCal Agenda Apple

### ISSUE THREAD

**Issue by RobHomey** [runely/calendar-homey#41]
When will it be possible to use the app with an Apple iCal agenda?

**Comment by runely** [comment]
Hi there.

Apple do not offer their iCloud calendars in publicly open ical/ics format (IETF standard RFC 5545). Instead they offer them in webcal/webdav format.

For now i don't plan to support anything else than ical/ics format.

There are articles out there explaining how to link Apple/iCloud calendars to other services:

- https://help.practicebetter.io/hc/en-us/articles/115000669508-Linking-your-Apple-iCloud-Calendar-to-Google-Calendar
- https://www.smsclientreminders.com/how_to_share_your_calendar_with_other_applications#icloud

**Comment by runely** [comment]
It appears that there's a way to get Apple iCal calendars to work in IcalCalendar. Look at this: https://github.com/runely/calendar-homey/issues/47#issuecomment-667274119

**Comment by runely** [comment]
Readme updated with steps for finding the iCloud calendar url 👍

**Comment by runely** [comment]
Readme updated with steps for finding the iCloud calendar url 👍

**Comment by RobHomey** [comment]
Hi,
 
Thanks for the update and mail. I have tested it and it works. 
I am happy that I can use the Apple Calendar.

Kind regards,
Rob
