### ISSUE TITLE
Request for new When-flowcard

### ISSUE THREAD

**Issue by johanstalnacke** [runely/calendar-homey#410]
Would love to have the When flowcard "A currently ongoing event i calendar xyz changed". Alternatively an ongoing-tag on the "An event changed in calendar xyz" containing a Yes/No.

Cheers!

**Comment by runely** [comment]
Can I ask what use case this would solve? The changed event trigger will fire for a changed ongoing event as well as for a changed non-ongoing event

**Comment by johanstalnacke** [comment]
I am using a google calendar to plan heating in my house. Based on hourly events in the calendar the heating system turns on or off. The "event started"-trigger allows me to trigger set the correct action in Homey (based on the title of the event). But sometimes I change my mind and replan the heating schedule for the day. This means changing the title of multiple events in the calendar, each which would trigger the "event changed"-trigger. But currently I can't figure out if any of these changes should trigger any immediate action for my heating system. The "event-changed"-trigger only tells me the title of the event, the  type of change, the earlier value and the new value. That is not enough to understand if the event is currently ongoing. Either the flag I suggested or the start and end times would solve the problem. Or perhaps the new flowcard I suggested.

Thanks!

**Comment by runely** [comment]
An ongoing

**Comment by runely** [comment]
In the next release, **1.12.0**, i've added the following boolean tags to the `Event changed` trigger:
- `Was ongoing` - Will show if the event was ongoing before the change
- `Ongoing` - Will show if the event is ongoing after the change

**Comment by runely** [comment]
v`1.12.0` is released to Homey App Store
