### ISSUE TITLE
Bug: Won't read clanedar

### ISSUE THREAD

**Issue by anderhau2** [runely/calendar-homey#412]
**Describe the bug**
I have had two calendars in there for a year. Suddenly one of them no longer responded, and it seems that only one of them is synced. I have tried to share it again and copy new ICAL link, but no. I use if "specific appointment" to check, and only items from one of my calendars is there. Both calendars is in the same account in office 365.

**To Reproduce**
1. Go to nee flow, if specific appointment, shows only appointments from one of my calendars. Hence, it does not react on the appointments as it did a month ago. 

**Expected behavior**

**Screenshots**

**Homey:**
 - Firmware: Last one for PRO
 - IcalCalendar version: Last one. Both updated. 

**Additional context**

**Comment by runely** [comment]
To be able to debug this i need some info/data.

Can you do the following:

1. Force a calendar synchronization by running/starting a flow with the action **Sync calendars** in it
1. After a couple of minutes send a diagnostics rapport from the app overview.
Choose **IcalCalendar** from the app overview -> Gear icon in the upper right corner -> Create diagnostics report

**Comment by anderhau2** [comment]
Her er debug koden:

84c5b38d-ea22-413b-8a28-9cd2fe9da968

Mvh
Anders Hauge
Tlf: 905 29847
________________________________

**Comment by runely** [comment]
There's nothing wrong beeing logged. I replied to the diagnostics report you sent. You should get an email to the address registered in your Homey account.

**Comment by anderhau2** [comment]
I got you message. I see that some of my appointments ended 31.12.2022. My bad!! But the appointment "Stue Senking Natt Ukedager" was there in my "Smarthus" calendar... It's also there in the ICS-file. I prolonged the appiontments that ended 31.12.2022 and now they are getting over, but not the one mentione above. I changed the plan with 1 minute, just to have something to save, and then it popped up. Wonderful strange ways of Microsoft mabe...:-)

Sorry for the major error on my part - with several of my most important routine appointments controlling the smarthouse ending 31.12!  Thanks! :-)

**Comment by runely** [comment]
Yes, the `Stue Senking Natt Ukedager` is in the ics-file but it was set to start at **25.05.2022** and end at **29.05.2022**. So it's correct that it was not imported!

```text
BEGIN:VEVENT
UID: *hidden*
SUMMARY:Stue Senking Natt Ukedager
DTSTART;TZID=W. Europe Standard Time:20220526T000000
DTEND;TZID=W. Europe Standard Time:20220529T140000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20230126T112125Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
```

**Comment by runely** [comment]
Good to hear you sorted it out 👍
