### ISSUE TITLE
Tags for current events

### ISSUE THREAD

**Issue by marium0505** [runely/calendar-homey#428]
Hey,

Love this app, and the current tags are very useful, but it would be great if you could add (duration and ends in) tags for current event.

I could for instance use it to decide whether it is time to reduce the target temperature on our floor heating (which I can do a few hours before we leave), or if it's still to early,

**Comment by runely** [comment]
I'm closing this since there's no feedback

**Comment by marium0505** [comment]
Apologies for the incredibly late reply. 

I mean the flow tokens that you can use anywhere (for instance in logic cards for etc), these ones: event_next_starts_in_minutes, event_next_stops_in_minutes and event_next_duration_minutes.

Would be very useful if you could add flow tokens for **stops in minutes** and **duration minutes** for current event. I would use it to decide when heating should stop etc.)

**Comment by runely** [comment]
There can be mulitple events which is currenly active. For instance, there can be an event which is active for multiple days, and there can be an event which is active for just a couple of hours.
This kind of feature would pick the event which was active first (and still is active), but that might not be the event you are expecting to see result from.

I think such a feature can get confusing, not to mention wrong at times. So i don't think this is something that is worth implementing. Sorry

**Comment by marium0505** [comment]
I guess having tags for the earliest and for the latest would be confusing as well? 

I personally only use this app for an calendar purely for events for when our summer house is in use, so I would never have multiple events running at the same time, but I get what you mean. 

I could always use the conditions, but I find it much easier to use variables (for instance I use it in a condition which checks if the number is between x and y to be able to do more controlled behaviour, for instance when an event begins/ends in between 24 and 48 hours). 

Thanks anyways, have a nice weekend!
