### ISSUE TITLE
Bug: AppCrash every minute

### ISSUE THREAD

**Issue by Ziglar1** [runely/calendar-homey#438]
Every minute the app crashes and restarts

**To Reproduce**
Create a flow that reports when an app crashes. 

**Expected behavior**
app not crashing and restarting

**Screenshots**
![Screenshot_20230315_165056_Homey](https://user-images.githubusercontent.com/17732290/225366118-acd6dd9a-bd9b-4f51-8425-2fc87c702469.jpg)

**Homey:**
 - Firmware: 10.0.0-RC.57
 - IcalCalendar version: 1.14.1

**Additional context**

**Comment by runely** [comment]
Sorry. I can't reproduce.
Tested with:
- Homey 2019 v8.1.3
- Homey 2023 v10.0.0-rc.57
- Homey 2023 v10.0.0-rc.58

To see what's happening on your end you need to send a diagnostics report from the app

**Comment by Ziglar1** [comment]
![Screenshot_20230315_194704_Homey](https://user-images.githubusercontent.com/17732290/225412566-3ce04f9f-9c66-4a83-8e67-fd06d120507e.jpg)
When sending a report i get this error message

**Comment by runely** [comment]
`Rate limited` is from Homey firmware and not the app itself.

Send a diagnostics report from **homey settings -> General**. This will send a diagnostics report to Athom. Please copy the diagnostics report code and paste it here

**Comment by runely** [comment]
Can you please create a flow with the trigger `Synchronization error occurred` from **IcalCalendar** and a timeline or push notification as action with the **Error** tag as message

**Comment by Ziglar1** [comment]
> `Rate limited` is from Homey firmware and not the app itself.
> 
> Send a diagnostics report from **homey settings -> General**. This will send a diagnostics report to Athom. Please copy the diagnostics report code and paste it here

87CE8B90

**Comment by Ziglar1** [comment]
> 

![image](https://user-images.githubusercontent.com/17732290/225426453-4c83faeb-4c52-4ea8-b774-c754512a5f71.png)

**Comment by Ziglar1** [comment]
> Can you please create a flow with the trigger `Synchronization error occurred` from **IcalCalendar** and a timeline or push notification as action with the **Error** tag as message

![image](https://user-images.githubusercontent.com/17732290/225426602-d809f1ca-4578-4e9c-b33c-bcbfa7030167.png)

**Comment by Ziglar1** [comment]
no timeline messages appear

**Comment by runely** [comment]
Then the app is probably killed by Homey firmware.

Have you tried to uninstall / reinstall the app?

**Comment by Ziglar1** [comment]
Update to RC58 did fix it. 
uninstall, Homey Reboot and install seems to have fixed it. no more crashes !

**Comment by Ziglar1** [comment]
Spoken too soon . After entering my Google calendar (secret url) the app crashes again.
![Screenshot_20230315_224038_Homey](https://user-images.githubusercontent.com/17732290/225450258-a2304d91-2667-4db2-9b69-35c70b103de3.jpg)

**Comment by Ziglar1** [comment]
https://calendar.google.com/calendar/ical/EMAIL%40gmail.com/private-ID/basic.ics

**Comment by runely** [comment]
Can you try with a different calendar url?

**Comment by runely** [comment]
Also, if there's a sync error, the error will be in the bottom of the settings window in red text, next to the save button.

If there's no error there this is most likely a homey issue. Which is most likely the case since you are presented with `Rate Limited` message.

Keep trying to send me a diagnostics report from the app. That's the only way I can have any chance to help you further at the moment

**Comment by Ziglar1** [comment]
a59ad50d-530d-4255-952c-e23b084018a6

**Comment by Ziglar1** [comment]
cf7c018f-fad3-4f61-934a-c1d3464356df

**Comment by runely** [comment]
You're homey are disconnecting and throwing `ping timeout` errors making the app crash.

This error has been reported by several people to Athom on slack. It's out of my hands I'm afraid 

![image](https://user-images.githubusercontent.com/25814673/225456368-00da30e2-4f2e-4fda-b783-a13180ade2f8.jpeg)

**Comment by Ziglar1** [comment]
thanks @runely , the problem seems to have resolved since Athom announced that the power brick is not strong enough. i have replaced the brick to a much stronger one and the app does not crash anymore.

**Comment by runely** [comment]
Thanks for the feedback! And I'm glad to hear it's working for you again!
