### ISSUE TITLE
Bug: Time of event is incorrect

### ISSUE THREAD

**Issue by hfaas** [runely/calendar-homey#439]
**Describe the bug**
Since a few weeks I have (old, reoccurring) events that are reported in Homey with a wrong time (offset). The time of the event in homey is 2 hours later that it is actually set for.

When I create new items it also not always goes well, from what I see...
Yesterday I created 2 items in the evening for about 30 min later, those came in just fine at the correct time. I also created a "working from home" (dutch Thuiswerken) event for coming monday from 8:30-17:00, but that one also is 1 hour shifted...

**To Reproduce**
I'm not sure I'm able to "reproduce" the issue, but it might be related to an earlier issue I reported about 1.5 year ago, since we never have been able to crack the code there... 
See also: [#266 ](https://github.com/runely/calendar-homey/issues/266)

**Expected behavior**
Reporting the correct time obviously.. ;-)

**Screenshots**
Events in Homey:
![image](https://user-images.githubusercontent.com/1212614/225557833-78c62fbe-8bb7-427a-bf21-d572e0ed3830.png)
Events in original (outlook) calendar:
![image](https://user-images.githubusercontent.com/1212614/225558209-4856ce8f-3c18-454f-a207-c8dfbaef665f.png)
Events from ical in google calendar:
![image](https://user-images.githubusercontent.com/1212614/225559756-72b7ff59-abe0-446b-8be0-64539beb93b0.png)

**Homey:**
 - Firmware: 8.1.3
 - IcalCalendar version: 1.14.1

**Additional context**
I'm living in the Netherlands (as probably also visible in the screens ;) ) which is at GMT+1.

**Comment by runely** [comment]
I need some info/data here.

Can you do the following:

1. Open settings for the app, and turn on `Log all events` and hit save!
1. Force a calendar synchronization by running/starting a flow with the action **Sync calendars** in it
1. After a couple of minutes send a diagnostics rapport from the app overview.

Choose **IcalCalendar** from the app overview -> Gear icon in the upper right corner -> Create diagnostics report

**Comment by hfaas** [comment]
Sure,

Here it is: e8875f32-31a6-42bf-a511-00f999964334

**Comment by runely** [comment]
Thanks.

This has nothing in commen with #266 .

The calendar provider you have used to create these events are creating your events with the timezone `Customized Time Zone` which is only valid for **Exchange**. The library used in **IcalCalendar** to parse the calendar data uses the `moment` library to guess which timezone `Customized Time Zone` could be dependent on the system its running on.

Since Homey **SDK3**, all Homeys are running in **UTC** timezone, no matter where in the world they are. This means that **IcalCalendar** absolutely needs to know which timezone an event is created in. And `Customized Time Zone` has no information and is therefore not enough to know which timezone this was created for, or if the event actually should have a timezone applied.

Thats why your events are showing up wrong!

To have them shown correctly in **IcalCalendar**, your events must be created in a valid timezone

**Comment by hfaas** [comment]
Hi thanks for your explenation, however I still don't fully understand...

Although I do understand that you use another library for the parsing of the date time, I have a feeling there is a bug in that library.
According to the Icalender specifications here: https://icalendar.org/iCalendar-RFC-5545/3-6-5-time-zone-component.html the VTIMEZONE, which defines the "Customized Time Zone", it should specify it's Timeszone referenced from UTC. In the VTIMEZONE block it also specifies the default offset as +1 from UTC and (if I understand te specification correctly) when Daylight saving is active it is +2. According to the same specification document (https://icalendar.org/iCalendar-RFC-5545/3-8-2-4-date-time-start.html) the DTSTART must be specified in "local" time when a VTIMEZONE is provided (which is a requirement when having Daylight saving in the timezone)!
So I still don't fully understand why it is showing up wrong if the specification is very clear, also in the fact that it isn't a ISO defined timezone shouldn't matter according to the specs.

Knowing the above, looking at the raw data.
`DTSTART;TZID=Customized Time Zone:20221219T083000`
The event starts at 8:30 (local time)
The UTC offset is +1, so the event is starting at 7:30 UTC (which is correct), instead in Homey it shows up at either 10:30 or 11:30 UTC time!...

Can you please elaborate?

**Comment by runely** [comment]
The timezone `Customized Time Zone` is not a valid timezone for any other than `Exchange`.

The library i use replaces `Customized Time Zone` with what it thinks it should be (hence `Customized Time Zone` should not be used!) and then **IcalCalendar** applies your timezone on top of that. That's what’s happening.

I have found a way to find the events where `Customized Time Zone` is applied and removes all timezones. Thats the best i can do.

I have release a new version, `1.15.0` with this fix!

**Comment by hfaas** [comment]
Hi Runely,

Thank you very much for the changes! they really helped!

By the way I do think the library you use, is misinterpreting the ICAL specifications, because there is nothing in the specification that says the TZID in VTIMEZONE _must_ be an ISO defined time zone (see also: https://github.com/runely/calendar-homey/issues/439#issuecomment-1475415568).
It even specifically says that fictive timezones (such as the `Customized Time Zone`) are allowed and as pointed out in my previous post, the offsets must (then) be according to UTC time.

Anyway; many thanks for the fix! it made every thing work properly again. 👍 👏
