### ISSUE TITLE
Day report

### ISSUE THREAD

**Issue by dannymertens** [runely/calendar-homey#44]
Hi,

Is it possible to get a daily report from a certain calendar?

What I like to do is get every morning when I wake up a summary of birthdays, important days I have for the day, maybe even better next 2 days

I have these events in a separate google calendar (family calendar)and added this to the app, but I also have 4 other calendars (family members, groups calendar) and just would like  to get a list from all the events in the birthday, jubilea calendar no need for the family members to see all the events in the members calendar, for that we also have the family calendar.

The problem is now that I can't or can't find an option to just get all the events from a separate calendar, is this possible? If not can this be added as a future request?

Thanks!

**Comment by runely** [comment]
Hi. Thanks for the feedback.

As of now there is now option to present events from just one specified calendar. I see your point and it would be a good addition to the app.

I will look into it 🙂
