### ISSUE TITLE
When apointment ends  from a spesific calendar missing

### ISSUE THREAD

**Issue by Sobergseth** [runely/calendar-homey#444]
If using many calendars there is possible to choose an action to start based on apointment in a spesific calendar, but there is not possible to stop an action when an apointment ends in a spesific calendar. The only solution is to choose when apointment ends, not to specify from which calendar. Can this be added? Now all calendars will trigger action, I just want a spesific calendar to trigger when apointment ends.

**Comment by runely** [comment]
`Event ends in ...` *could* be added, and probably should be added to easier see the functionality.

In the meantime, the functionality you are asking for is already possible to achieve like this:

1. Use the `Event ends` trigger card
1. In the **AND** section use a *Logic -> Text is equal* card.
    1. For the *Text* argument choose the **Calendar Name** tag from the trigger card.
    1. For the *Value* argument put in the name of the calendar (exactly as setup in IcalCalendar) you want to get triggered by

With this your flow will only trigger when the event ends from the calendar you set in the AND section

**Comment by runely** [comment]
Trigger card `Event ends from calendar` will be added to the next release
