### ISSUE TITLE
Notice-Field as Tags (Flow-card "if")

### ISSUE THREAD

**Issue by notbuch** [runely/calendar-homey#447]
Ical for homey is such a great lovely app.

would it be possible to get the "Bermerkung" or "notizen" field as a tag for a flow?

Thanx so much!

Stefan

**Comment by runely** [comment]
I'm glad you enjoy the app 🙂

The `note` field can be added as a tag to the trigger cards.

However, not all calendar providers exposes notes in to the **.ics file**. For instance is Office 365 one of those.

**Comment by runely** [comment]
As a matter of fact, **Apple calendar** and **Gmail calendar** uses the `description` field for notes.

The description field is already present as a tag. So for these two providers, and any other providers who uses the description field for notes, this is already present.

Which calendar provider are you using?

**Comment by notbuch** [comment]
Hi Rune,

thanx so much for the answer. I didn't notice, that notice is a tag in a flow from the right flowcard. I will try (I use google calendar). This was the missing link for me. I love your app and it is great helpful. Is there a donate possibility?

Thanx!

Stefan from Germany

**Comment by notbuch** [comment]
actually it would be cool, the "note"-tag of a calendar-entry would also be available here (screenshot)? because then the starting of the flow would not necessarily depending of a ical start card. :-) 
![image](https://user-images.githubusercontent.com/85675943/234308110-fc9f2ed1-f5b4-412f-b4b3-94994fd86647.png)

**Comment by notbuch** [comment]
And it wouzld be cool, if the starting cards can be filtered by calendar, because I can't filter the starting function with "and" cards. Example: A new event is edited in calendar x. that is not possible to filter later.... 
![image](https://user-images.githubusercontent.com/85675943/234517338-583ec6ef-24f6-427f-b38d-35646e5a4355.png)

**Comment by runely** [comment]
> actually it would be cool, the "note"-tag of a calendar-entry would also be available here (screenshot)? because then the starting of the flow would not necessarily depending of a ical start card. :-) ![image](https://user-images.githubusercontent.com/85675943/234308110-fc9f2ed1-f5b4-412f-b4b3-94994fd86647.png)

<br><br>The `description` field can indeed be created as a global tag.

***FYI: The global tags always shows the next upcoming event, so when an event is started, these global tags are repopulated with info for the next upcoming event (if any)***

**Comment by runely** [comment]
> And it would be cool, if the starting cards can be filtered by calendar, because I can't filter the starting function with "and" cards. Example: A new event is found in calendar x. that is not possible to filter only that calendar later (only by logic).... ![image](https://user-images.githubusercontent.com/85675943/234517338-583ec6ef-24f6-427f-b38d-35646e5a4355.png)

<br><br>I don't know German so it’s kind of hard to understand. Is it the `Event added` trigger card you want to be able to filter by calendar? Meaning having a new trigger card, **Event added in *calendar*** ?

**Comment by notbuch** [comment]
Thanx runely, sorry, I know, the language.....

yes, the "description"-tag is only available, when it begins with an ical-start-flow-card. I know. I think it would be cool, that "event begins" or "event ends" or something like that would be also filterable for the calendar (my workaround is an "and"-logic-card looking for the triggered calendar-name). The workaround is fine as well.

But I have no workaround if not using the ical-starter-cards regarding the "description"-tag. It would be cool, if there were the possibility to get it anyway as a tag like the others that are available without starting the flow by an ical-card.  :-)

**Comment by runely** [comment]
**Event starts from *calendar*** and **Event ends from *calendar*** is already present as trigger card

<img width="1077" alt="Skjermbilde 2023-04-27 kl  16 55 12" src="https://user-images.githubusercontent.com/25814673/234902723-2ec12710-fa9e-4f8a-a01b-f5ad95b07f42.png">

**Comment by notbuch** [comment]
Thanx runely, sorry for that, I didn't explained good enogh. I ment the added and changed card. :-) And It would be cool to support you,  but I can't find how. maybe you can send me a pm at homey forum. :-)

**Comment by runely** [comment]
New version, **1.18.0**, is in review and soon released to the App Store.

This version has these additions:
- Added `Next event description` , `Next event description in %calendarname%` and `Description (contains)` as global tokens
- Added `Event added in calendar` and `Event changed in calendar` triggers
