### ISSUE TITLE
IcalCalender problems with the URI link to the .ICS file

### ISSUE THREAD

**Issue by copiis** [runely/calendar-homey#453]
Have the IcalCalender in use.
I have now switched from Nextcloud to Vivaldi Calendar. With the Nextcloud link to calendar it worked with the Vivaldi calendar it does not work although that is also a ICS link.

Created a test calendar and the link looks like this.

https://webmail.vivaldi.net/?_task=calendar&_cal=Y29waWlzQHZpdmFsZGkubmV0OjE1NTAxMw%3D%3D.ics&_action=feed

But when I enter this link the error message comes up
![2023-05-22 00 15 56](https://github.com/runely/calendar-homey/assets/12480023/be2cf038-4d32-479c-91e9-68a423ff1e38)

**Comment by runely** [comment]
Status code 401 is `Unauthorized`.
If you try to open the link in a browser, you'll see that it requires a username and password.

For **IcalCalendar** to work, the link must be publicly available and have no authorization enabled.

Apple, Google and Office365 for instance is offering a secret link to the calendar. Maybe Vivaldi has something similar?

**Comment by copiis** [comment]
Wouldn't it be possible to add authentication?

**Comment by runely** [comment]
All the major calendar providers provide a way to have a secret ics link. So, no, there's no plan for adding that.

**Comment by copiis** [comment]
It should be this link, it does the same thing the Google calendar link does, it downloads the ics file when you click on it, but that doesn't work in IcalCaleder.

https://webmail.vivaldi.net/?_task=calendar&_cal=Y29waWlzQHZpdmFsZGkubmV0OjE1NTAxMw%3D%3D.ics&_action=feed

**Comment by runely** [comment]
This link presents a username/password dialog.

So no, this link is not the same as the secret link google provides, and a link with a username/password dialog presented won't work in **IcalCalendar**!

![image](https://github.com/runely/calendar-homey/assets/25814673/ba57076c-989d-4f91-bcb5-91e461d84df0)

**Comment by copiis** [comment]
I switched to Google
