### ISSUE TITLE
Bug: Short descriptive bug title here

### ISSUE THREAD

**Issue by Jasper27NL** [runely/calendar-homey#460]
**Describe the bug**
Sinds a few Days/weeks one of my calenders is not working anymore with Homey
Noticed last week that i was not getting an update. 

**To Reproduce**
There are no calender reminders anymore for one of my calanders. 
Other still working fine. 

Callender that is not working (was working before)
https://wasteprod2api.ximmio.com/api/CallIcal?cn=Avalex&x=f7a74ad1-fdbf-4a43-9f91-44644f4d4222&ty=&ua=0907d852d90cec6948da1a644364b3c1510384c1&sd=2022-12-25&ed=2024-01-27&path=https://wasteprod2api.ximmio.com&ln=nl&nt=7

**Expected behavior**
Within Homey the tags are empty for the calender. 
Homey does see the calander name that i gave it but the output is empty

**Screenshots**
![image](https://github.com/runely/calendar-homey/assets/137485892/6d06cf40-7c64-4021-9011-3aaf87cc9a82)

**Homey:**
 - Firmware: 8.1.4.
 - IcalCalendar version: v1.18.4

**Additional context**

**Comment by runely** [comment]
Can you please restart the app, and after 5 minutes send a diagnostics report from the app settings

**Comment by Jasper27NL** [comment]
Here you go. 8d9d60d8-da0d-44ad-bc08-1176d5f78b30

**Comment by runely** [comment]
There’s no events to import:

```text
[log] 2023-06-23 09:48:54 [IcalCalendar] getEvents: Events for calendar 'Avalex' updated. Event count imported: 0. Total event count in calendar: 0
```

**Comment by Jasper27NL** [comment]
But when I load the calender in my Google calander it shows events.
![image](https://github.com/runely/calendar-homey/assets/137485892/6e7765a4-4539-448b-a594-0d7f0181affe)

**Comment by runely** [comment]
The URL you are using isn't working. Well, actually the URL in itself is working since it returns 200 OK, but it doesn't send back anything.

So you need a different URL.

<img width="542" alt="image" src="https://github.com/runely/calendar-homey/assets/25814673/8ac4388b-2b0f-4a63-b6ef-da0697db9428">
