### ISSUE TITLE
Apple iCloud Calendar doesn't work

### ISSUE THREAD

**Issue by iAmRenzo** [runely/calendar-homey#47]
For some reason Apple iCloud iCal files won't load. Probably because another format (it's is Apple, right).

If you need assistance with an iCloud calendar format or something: happy to help! :)

**Comment by runely** [comment]
Hi there.

Apple do not offer their iCloud calendars in publicly open ical/ics format (IETF standard RFC 5545). Instead they offer them in webcal/webdav format.

If you know about a nodejs library which handles/parses those calendars without the need for username/password, i can look into it.

There is however the possibility to link your Apple Calendar to eg. Google Calendar and use Google Calendar in IcalCalendar:
- https://help.practicebetter.io/hc/en-us/articles/115000669508-Linking-your-Apple-iCloud-Calendar-to-Google-Calendar

**Comment by MatsAnd** [comment]
@runely / @iAmRenzo  - Have you tried just replacing **webcal://** with **https://** in the iCloud calendar url? 
That worked for me... [Example .ics file](https://p20-caldav.icloud.com/published/2/MTQyMjY3NTQxMTE0MjI2NyiAZpe5oOx5AkUjQmF66YNswr_V871OKLSRT_tEWUm-w0O1uxi_CVZHlogbRiojSCwdvF1keNoVNAWSHe7OQEw)

**Comment by runely** [comment]
Hey, look at that. That works! Thanks @MatsAnd 👍

**Comment by runely** [comment]
Readme updated with steps for finding the iCloud calendar url 👍

**Comment by iAmRenzo** [comment]
Thanks for the effort, but I am not ousing nor willing to use a Google Product.
@MatsAnd I'll try that.
