### ISSUE TITLE
Bug: Short descriptive bug title here

### ISSUE THREAD

**Issue by RenvanRoo** [runely/calendar-homey#497]
**Describe the bug**
Sync problem

How can i check if Sync works?
Now i create a flow for syncing every 15 minutes en it's working. Whitout this flow, itś not working anymore.

**Comment by runely** [comment]
Hi there. Have you had a look at the forum article? Your questions are answered there:

[Sync](https://community.homey.app/t/app-pro-icalcalendar/80708#sync-4)
[See a list of which events exists in the app](https://community.homey.app/t/app-pro-icalcalendar/80708#see-a-list-of-which-events-exists-in-the-app-5)
[Troubleshooting](https://community.homey.app/t/app-pro-icalcalendar/80708#troubleshooting-13)

**Comment by RenvanRoo** [comment]
Yes i did and i see the agenda-items in the list. Something is going wrong in the flow. Iḿ testing it now.

**Comment by RenvanRoo** [comment]
Report 87FCC6F2

I can't remove any card en the flows don't react any more.

**Comment by runely** [comment]
That diagnostics report is for the homey team. You have to send a diagnostics report from the IcalCalendar app settings screen

Have you added a flow with the `Synchronization error occured` trigger? This flow will notify you if there are any sync issues or in fact any other issues in the IcalCalendar runtime.

**Comment by RenvanRoo** [comment]
Oke, i just added that flow. So far, no issues. I send Homey the report. Thanks

**Comment by runely** [comment]
I got a diagnostics report now, I’m guessing that is from you.

Your calendar contains in total 6611 events! That is a big calendar to import! IcalCalendar needs to download the whole ics file, parse it and figure out which events it should import.

Out of these 6611 events, only 87 are imported.

I see from the diagnostics report that Homey is warning about memory limit for the app, and the app then crashes.

Try to clean up your calendar and significantly decrease the size of your calendar, and I think you should be good to go again

**Comment by RenvanRoo** [comment]
Oké! 
I can try to change the period of time what icalcalendar imports. Is that a possibility?
I need all of my agenda-items, so that can't be changed.

**Comment by RenvanRoo** [comment]
I made it 3 days now. See what happends...

**Comment by RenvanRoo** [comment]
If i make a new report, can you see how much items there are now?

**Comment by runely** [comment]
You can try to adjust the timespan, but I doubt it will have any effect. 

I suspect the calendar you are importing from is too big

Could you try with a different calendar to see if the problems persist?

**Comment by RenvanRoo** [comment]
I made a new report.
Can you see how many items still there? I set it now on 1 day.
Does this app also get the older items then today? Perhaps thats a problem?
Manually testing oké; automatically NO.

Op di 11 jul 2023 om 20:42 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by RenvanRoo** [comment]
What I see is that when the time is there, the Ical-cards sometimes go
grey. Nothing happens then.
No Push or timeline messages when the time is there!.
I checked the agenda-items and I can see them in the list of which events
exists. Even the timestamp is correct and nothing happens.
When I do it manually (test from here); then it works.

Why is it that the Ical-cards went grey several times a day?

What I saw on another topic:
Welcome, there are several reports of notifications not working as they
should on Homey Pro Early 2023, not just from the Heimdall app but also
others. You could try recreating the flows you’re using to write to the
timeline. If that doesn’t help, please report this to Athom.


Please help me. It worked on my Pro 2019, now a Pro 2023 and the app is
dead.


Op di 11 jul 2023 om 22:01 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by runely** [comment]
So far, the only problems i have seen in the logs is that your calendar is too big. Can you try with a different calendar, one that is smaller

**Comment by RenvanRoo** [comment]
I think the problem is with the time before an item begins. When I use no
time, it's oke. When I say in a flowcard the item begins, for example, 90
minuts before, nothing happens.
I used also another agenda and the problem is the same.

Op di 11 jul 2023 om 23:45 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by RenvanRoo** [comment]
The flow is named "Rune".
I search for "Rune" on my agenda, it starts over 90 minutes. I can find it
in de list after I synced my agenda!

I just send you the report.

Op wo 12 jul 2023 om 10:00 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by RenvanRoo** [comment]
Sorry, I just send you an incorrect flow. Excuse me.

**Comment by runely** [comment]
There was one trigger with the trigger card `Event starts` at 10:16

```text
// datetime is in UTC
2023-07-12T08:16:00.020Z [log] [IcalCalendar] triggerEvents: Triggered 'event_starts' without state for '70s3edph6osjgb9l6os34b9kc9gj2b9o65ijebb6cop30c1i6tij6c9l6g@google.com'
```

The event `Rune` is set to end at 12:45, meaning that 90 minutes before would be 11:15. The log i received did only contain log items up until 10:30

```text
// datetime is in UTC
2023-07-12T08:16:00.033Z [log] [IcalCalendar] checkEvent: Next event containing found: 'Rune' Wed Jul 12 2023 12:45:00 GMT+0200. Ends within 90 minutes? false
2023-07-12T08:27:14.190Z [log] [IcalCalendar] checkEvent: Next event containing found: 'Rune' Wed Jul 12 2023 12:45:00 GMT+0200. Ends within 90 minutes? false
```

And then at 10:28 you updated the event `Rune` to start at 12:00 and end at 13:00, meaning that 90 minutes before would be 10:30 for the start part and 11:30 for the end part. The log i received did only contain log items up until 10:30

```text
// datetime is in UTC
2023-07-12T08:28:28.205Z [log] [IcalCalendar] Updated event - Summary: 'Rune' -> 'Rune' (false) , Start: 'Wed Jul 12 2023 11:45:00 GMT+0200' -> 'Wed Jul 12 2023 12:00:00 GMT+0200' (true) , End: 'Wed Jul 12 2023 12:45:00 GMT+0200' -> 'Wed Jul 12 2023 13:00:00 GMT+0200' (true) , Description: 'undefined' -> 'undefined' (false) , Location: 'undefined' -> 'undefined' (false)
2023-07-12T08:28:50.524Z [log] [IcalCalendar] checkEvent: Next event containing found: 'Rune' Wed Jul 12 2023 12:00:00 GMT+0200. Starts within 90 minutes? false
```

Can you take a screenshot, or share your flows, and paste them here.

It's kind of hard to see if there is anything wrong here when times are all over the place...

**Comment by RenvanRoo** [comment]
Hello,

This is two simple flows. It wont' t work automaticly. Manually it does.
The other flows, I have deleted them, to create a clean start again.

I send you a report again.

Op wo 12 jul 2023 om 12:48 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by RenvanRoo** [comment]
The photo is to big. one moment

**Comment by RenvanRoo** [comment]
It's an advanced flow. I can't share

**Comment by RenvanRoo** [comment]
Now I get a notificatie, but it's 4 minutes later than aspect.
I try again en te flow has to trigger a agenda item at 14:00!
It starts over 90 min. so in the agenda there is an item at 15:30.
I can see te correct time in the list of all my items.
Let's see what happens....

**Comment by RenvanRoo** [comment]
Now it's 14:02 and nothing happend.
I test the flow at 14:03 myself and it works!! 
I send you te report.

**Comment by RenvanRoo** [comment]
My flow Rune

Op wo 12 jul 2023 om 12:48 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by RenvanRoo** [comment]
I send you the screenshot!

Op wo 12 jul. 2023 14:46 schreef Rune Moskvil Lyngås <
***@***.***>:

**Comment by runely** [comment]
Just remember you can't send attachements via mail into GitHub. You have to log on to GitHub and add the attachements to this issue yourself

**Comment by RenvanRoo** [comment]
![IMG_20230712_134358](https://github.com/runely/calendar-homey/assets/139113122/3178f587-cfcf-40e6-aa7c-9cc3ec74c13a)

**Comment by runely** [comment]
You are using the regular `Event starts` trigger which will ONLY trigger when the event starts! When in fact you should have used the trigger `Event start over`

Then you are using a condition card to check if event `Rune` in calendar `RvR` will start within 90 minutes, which will be kind of true, since that event just started. So when the event `Rune` starts, you will get a push notification with `Hello! Rune`.

Then you are using a second condition card to check if an event by the name `Vroeg` starts in 5 mintes...

I think you have misunderstood the **IcalCalendar** triggers.

I'm guessing you instead want to use the trigger `Event start over` with Aantal set to 90 Minuten for the first flow. And the trigger `Event start over` with Aantal set to 5 Minuten for the second flow.

**Comment by RenvanRoo** [comment]
Sorry, Sorry, Sorry. It was my own mistake. Sorry! Now, it works again with the right cards.
Thank you for your patiance.
