### ISSUE TITLE
Homey disables the flow

### ISSUE THREAD

**Issue by Ortush** [runely/calendar-homey#498]
Everytime I use the card "Calendar event stops in 10 minutes" my flow gets almost instantly disabled because it's been running too many times.

Add a "When" card like above. Then connect it to an "And" card that says "The title of the event is exactly "xx". And if this is true turn on a light.

I expect it to not disable the flow.

**Homey:**
 - Firmware: 10.0.0-rc.122
 - IcalCalendar version: 1.19.1

Homey Pro 2023

**Comment by runely** [comment]
Can you follow the list under [`Any other problems`](https://community.homey.app/t/app-pro-icalcalendar/80708#any-other-problems-15) and send me a diagnostics report

**Comment by Ortush** [comment]
f74df5a2-d55c-414c-a7d2-d7f5784e492f

**Comment by runely** [comment]
I don't see anything wrong in the diagnostics report. Could you enable the flow that uses `Calendar event stops in 10 minutes` and when it has been fired send me a new diagnostics report

**Comment by Ortush** [comment]
Problem is that the flow is disabled within seconds of configuring the Calendar event stops in 10 minutes.

**Comment by runely** [comment]
Thats OK. I will still be fired and I can probably see something in the logs

**Comment by Ortush** [comment]
It should have fired in this report: 4c782d00-9134-40b3-87b6-91ca2b7f8322

**Comment by runely** [comment]
There's no trace in there for any trigger card been triggered. The diagnostics report contains log items between 21:15:15 and 21:26:00 today, so i guess the flow triggered before 21:15:15. It should have been logged to your timeline when the flow was disabled. What timestamp does that say?

Could you also please restart the app, and send me a diagnostics report 2 minutes after restart?

**Comment by Ortush** [comment]
8eaf3e48-aa73-4ba7-844e-655a97096802
The flow was disabled at 22:05:00.
No calendar event active.

7a71c028-678d-4d60-bb9c-c5bccb6ac5cb
The flow was disabled at 22:08:00
Calendar event active that ends 22:20

Seems like the flow is disabled everytime a new minute starts. 
The flow is active but as soon as the clock ticks over to another minute it's being disabled. The flow is always disabled at the exact minute. 22:05:00, 22:08:00 an 22:11:00 and so on.

**Comment by runely** [comment]
There's nothing in the logs showing that a card was triggered.

```text
2023-07-11T20:04:32.470Z [log] [IcalCalendar] getEvents: Created next event with token 'ical_calendar_next_with_description'
2023-07-11T20:05:00.005Z [log] [IcalCalendar] startJobs/trigger: Triggering events and updating tokens
2023-07-11T20:05:00.007Z [log] [IcalCalendar] getEventsToTrigger: Checking calendar 'Mattias och Emilie' for events to trigger
2023-07-11T20:06:00.068Z [log] [IcalCalendar] startJobs/trigger: Triggering events and updating tokens
2023-07-11T20:06:00.069Z [log] [IcalCalendar] getEventsToTrigger: Checking calendar 'Mattias och Emilie' for events to trigger
```

```text
2023-07-11T20:08:00.006Z [log] [IcalCalendar] startJobs/trigger: Triggering events and updating tokens
2023-07-11T20:08:00.008Z [log] [IcalCalendar] getEventsToTrigger: Checking calendar 'Mattias och Emilie' for events to trigger
2023-07-11T20:09:00.043Z [log] [IcalCalendar] startJobs/trigger: Triggering events and updating tokens
2023-07-11T20:09:00.044Z [log] [IcalCalendar] getEventsToTrigger: Checking calendar 'Mattias och Emilie' for events to trigger
```

**Comment by runely** [comment]
Can you restart the app and then send me a diagnostics report 15 seconds after that?

**Comment by Ortush** [comment]
143fec67-ece5-4e13-801a-be4533ab5f26
Flow disabled 04:53:03 according to timeline.

**Comment by runely** [comment]
Hmm. I’m not receiving the whole log.

Could you try this:

1. Disable the flow that uses the trigger card `Calendar event stops in 10 minutes`
1. Create a new flow with the trigger `Flow -> When this flow is started`
1. And use the action card `Synchronize calendars` from IcalCalendar
1. Then, manually start this flow from the computer via my.homey.app and from the mobile send a new diagnostics report 5 seconds after the flow was started

**Comment by Ortush** [comment]
OK here it is:
3b54e603-5cec-4b7b-8f53-f3d0a45a52d9

**Comment by runely** [comment]
I'm sorry, but you have too many events imported. So the log sent is cropped. I don't receive the whole log. Just the end of it.

Could you please decrease how long you import events, to like 3 days or something, and then do the same thing again by sending me a diagnostics report

**Comment by Ortush** [comment]
No problem, bf6f6964-9ee3-4bcf-bee8-1688383f1d2c

**Comment by Ortush** [comment]
I tried activating the previous flow and it worked when I reduced the number of events imported. Seems like that was the problem.

**Comment by runely** [comment]
Hmm. It seems that the app is beeing shutdown by Homey right after startup.

Has your Homey too much to do? Is there any available resources? If you go to More -> Settings -> General -> Memory. How much memory have been used? And how much memory is IcalCalendar using?

Do you have the new improved power adapter? If not you might be experiencing underclocking of the CPU. Please install this app, https://homey.app/no-no/app/com.sysInternals/sysInternals/, and add the Homey Pro 2023 device for it. It will tell you if you have any CPU alarms or if you system is overloaded
