### ISSUE TITLE
Bug: Short descriptive bug title here

### ISSUE THREAD

**Issue by Skippy0013** [runely/calendar-homey#500]
**Describe the bug**

When I create a flow: "when an appointment starts in 1 hour","send me a notification"  Then it turns off with the comment: "flowname" is disabled because this flow was run too many times.

**Homey:** 
Homey pro (Early 2023)
 - Firmware: 10.0.0-rc. 133
 - IcalCalendar version: latest version 2.0.0, but also did this with previous version.

**Comment by runely** [comment]
Look at this issue and see if this applies to you aswell.

And send me a diagnostics report

**Comment by runely** [comment]
Any update on this? I will close the issue as completed within 3 days if no response

**Comment by Skippy0013** [comment]
fd2c523b-0ee6-40e4-904d-ea0e720ce6b9

**Comment by runely** [comment]
There is no issues in the diagnostics report you sent! Everything seems fine.

Did you have a look at the issue I posted earlier, nr 498?

Post a screenshot of your flow
