### ISSUE TITLE
Bug: Request failed with status 503

### ISSUE THREAD

**Issue by TVDL911** [runely/calendar-homey#508]
**Describe the bug**
Initially, the IcalCalender (and created flows) works perfectly. After a few hours, the flows no longer work. After further investigation it appears that the configuration screen says "Request failed with status 503". Refreshed the calendars several times, deleted the app and restarted Homey Pro several times. After several hours the problems return.

**To Reproduce**
1. Go to Settings
2. Click on IcalCalender
3. Scroll down to Configuration
4. See error Request failed with status 503

**Expected behavior**
I expect the calendars to remain synced.

**Homey:**
 - Firmware: 10.0.1-rc.1
 - IcalCalendar version: V 2.0.1.

**Additional context**

Screenshot [https://freeimage.host/i/Ht0dRgj](url)

**Comment by runely** [comment]
The HTTP code 503, means your calendar providers server is not ready to handle the request.

Can you send me a diagnostics report?

**Comment by TVDL911** [comment]
> The HTTP code 503, means your calendar providers server is not ready to handle the request.
> 
> Can you send me a diagnostics report?

Ofc! 633c8527-5048-42e3-a63b-6933b9612672

**Comment by runely** [comment]
Your calendar named `W` has a url registered that's not working. When visiting the url, the server returns a 503 error.

You need to find the correct url from you caledar provider.

**Comment by TVDL911** [comment]
> Your calendar named `W` has a url registered that's not working. When visiting the url, the server returns a 503 error.
> 
> You need to find the correct url from you calendar provider.

Thanks for your swift reply.

For example, the link of my calendar called W is: webcal://p50-caldav.icloud.com/published/2/MTMxNjI3NTYyNTEzMTYyN1oZCLwNyDAcl5WVRFhcOi1uz7lpAO87v56bJTjwrKn6ydWjNS2Fs3207f-rQRmC--9xFO5-8jMjIB6Acma4_9c

When I put this link in the config screen, it's transformed to: https://p50-caldav.icloud.com/published/2/MTMxNjI3NTYyNTEzMTYyN1oZCLwNyDAcl5WVRFhcOi1uz7lpAO87v56bJTjwrKn6ydWjNS2Fs3207f-rQRmC--9xFO5-8jMjIB6Acma4_9c

With other words; without the "webcal" it isn't working. How can I arrange this?

Thanks again!
