### ISSUE TITLE
Getting [null] when requesting calendar entries

### ISSUE THREAD

**Issue by Fred0172** [runely/calendar-homey#515]
**Describe the bug**
Created a flow in homey and by action I request the events for the next day, I receive feedback but always as [null]

**To Reproduce**
1. create flow When time is, No And, Then sync calendar / push notification to phone of user action Event for tomorrow
2. Receive notification on phone

**Expected behavior**
get message on phone with events for tomorrow

**Screenshots**

**Homey:**
 - Firmware: Homey (Early 2018) Version 8.1.0
 - IcalCalendar version: V2.0.2

**Additional context**
This was working correct for a long time, but out of no where it gives me the [null] message
Also when I create a card to say my events on google hub is says null

**Comment by runely** [comment]
Homey firmware 8.1.0 is outdated by 7 versions.. Please upgrade to the latest firmware first.

If you're having the same problem after upgrade, then send a diagnostics report, and paste the code here

**Comment by Fredenator** [comment]
Runely,
Sorry for the mix up I was  under the impression that my Homey was  on auto update, thanks all working after firmware update
