### ISSUE TITLE
"Ghost" event in output

### ISSUE THREAD

**Issue by EsbenRasmussen** [runely/calendar-homey#526]
Hi Rune

With all your great improvements I am finally able to implement this.

However, I have just run across a weird issue.

As expected I get the event titles from my calendar - but also a title from a recurring event which I had running 3 years ago but then stopped.

This event is not shown in my calendar for the time period the app sync is set to use.

I can't quite figure out whether it is a bug in Google Calendar or if there is a clash within your app.

Do you have any suggestion for me on how to start bug-hunting before reporting anything further?

**Comment by EsbenRasmussen** [comment]
OK I managed to remove the "ghost" title.

My "fix" was to open Google Calendar and search for the event (which it found occurrences for back in 2020). I then clicked on one of the occurrences and chose to delete all occurrences.

Though still not sure why it was part of the recent next two day synchronization.

I am closing this for now.

**Comment by runely** [comment]
Hmm. Too bad you removed the event. Would be interesting to see what was going on.

Oh well.
