### ISSUE TITLE
Option to have contains in and card

### ISSUE THREAD

**Issue by jeroendew** [runely/calendar-homey#529]
**Is your feature request related to a problem? Please describe.**
Im using the card "Calendar _Choose calendar..._ has event where _..._ is equal to _Search value..._ 
But for now it is only possible to match the exact value.

**Describe the solution you'd like**
I would like to have a dropdown with some more options like, _equals to, contains,  starts with _?

**Comment by runely** [comment]
Added a new version (which is in review) with more possibilities in the condition card.

The current condition card has been deprecated, and a new one with more possibilities has been added.

The test version can be found and tested here: https://homey.app/no-no/app/no.runely.calendar/IcalCalendar/test/

**Comment by jeroendew** [comment]
Thank you for the quick fix. The only thing i'm missing (don't know if possible) to have tag that i can use. Like the title, start time event, location. Is this also possible with this card?

**Comment by runely** [comment]
> Thank you for the quick fix. The only thing i'm missing (don't know if possible) to have tag that i can use. Like the title, start time event, location. Is this also possible with this card?

No, this is not possible with condition cards. Tags are only possible with triggers, because a trigger is for a specific happening.
A condition card can be for one or many.
