### ISSUE TITLE
Calendar event with tag

### ISSUE THREAD

**Issue by lysdioden** [runely/calendar-homey#548]
![Skärmbild 2023-11-15 102758](https://github.com/runely/calendar-homey/assets/119966816/8e529823-370c-4002-9f87-c63865cd0b62)
Hello.
I have had this flow for almost a year but now it has stopped working, the last time it worked was 20/10, what is wrong or have I missed something?

**Comment by runely** [comment]
You don't mention anything about which app version you have installed or which Homey device you have. Can you please add some more info?

Nothing that i know of happend 20.10..

Have you verified the following:
1. That the tag `Motorvärmare til jobbet` actually contains the value you need?
2. That the the flow card `En händelse startar om ... Minut(er)` actually is being triggered by adding an action card directly to that flow card? For instance a push message to your phone or a timeline notification.
3. That there is imported events that satisfies the logic in the trigger card making it trigger?

If you are running app version >= **2.3.0**, have you checked out the `Hit count` in the settings? It will tell you how many times a trigger card is triggered, and when it was triggered last time

**Comment by lysdioden** [comment]
Hi
I have app version 2.3.0 Homey pro Early 2019 firmware 10.0.2

I have this flow to start the engine heater before work.

It is triggered by my calendar when I start my jobb and should be started a certain time before depending on the outside temperature.

I have checked the Hit count but these triggers are not there

**Comment by runely** [comment]
Again, have you verified that the trigger isn't being triggered? Or are you just assuming that it doesn't work?

The logic after the trigger card might be preventing a full run through.

Please add a push message or timeline notification directly to the trigger card to see if it is being triggered when you think it should be.

And can you post a screenshot of the Hit count table? The trigger should be there with the value of the tag you are using

**Comment by runely** [comment]
Are you still having trouble with this flow @lysdioden ?

**Comment by lysdioden** [comment]
Hello.
I've done some testing and that's when I use a tag to delay the start of the trigger.
if I were to replace the tag and write there, for example, 120 minutes, it works. but since I want it to vary, I have to control it with a tag

**Comment by runely** [comment]
I just tested the use of a tag in a similar flow and it is working. If the card isn't triggered in your flow when you add the tag , but the card is triggered when you manually put in a number I can only assume that there is an error with your tag.

![image](https://github.com/runely/calendar-homey/assets/25814673/18cff33c-d3ac-47e6-81ed-8fe5fbe2aac4)
