### ISSUE TITLE
Second, third, ASO. Calendars doesn't trigger any event on startingtime

### ISSUE THREAD

**Issue by BjornSchalks1976** [runely/calendar-homey#559]
Second, third, ASO. Calendars doesn't trigger any event on startingtime

**Comment by runely** [comment]
Please give some more information..

Homey version
Homey firmware
IcalCalendar version

Please send a diagnostics report

And please post a screenshot of your Hit Count table from the settings in the app

**Comment by BjornSchalks1976** [comment]
Homey version: Homey Early 2023
Homey firmware: 10.2.1
IcalCalendar version: 2.6.0

![image](https://github.com/runely/calendar-homey/assets/154658728/93fe0140-dcbf-42b2-8c98-26856cb6c602)
![image](https://github.com/runely/calendar-homey/assets/154658728/fa9d12aa-f0e3-4d89-985e-234fc5cc222d)
![image](https://github.com/runely/calendar-homey/assets/154658728/d1a6b826-c19b-428b-a5c0-3a63c71be288)

**Comment by BjornSchalks1976** [comment]
Eventstart does not trigger any events on second, third eso Calenders

**Comment by BjornSchalks1976** [comment]
c8d93f8c-8d97-4511-a0b4-ab188fbd7986

**Comment by runely** [comment]
I'm sorry, but there's nothing useful in the diagnostics report.

Please do the following:

1. Make a new event which will start later today or tomorrow (as long as the start date is within the time frame being synchronized in to the app)
2. Open the settings page for the **IcalCalendar** app
3. Scroll down to the bottom and enable `Log all events` (blue checkmark)
4. Click **Save**
5. Restart the app
6. Wait 4 minutes
7. Click `Create diagnostics report` on the app gear icon.
8. Let me know the title of the event you created so i can find it in the diagnostics report and see what datetime it's imported as.

**Comment by runely** [comment]
Closing as complete as there's no feedback
