### ISSUE TITLE
Event starts in ....

### ISSUE THREAD

**Issue by jango61** [runely/calendar-homey#56]
Hello developer,

I use your program icalcalendar but I like to have the possibility to have a setting larger than 60 minutes before an event happens.
Is it possible to add  a .... hours option?

Kind regards,

Jaap

**Comment by runely** [comment]
Hi

There will be more choices in the new version.

[Added more timespan choices to triggers/conditions](https://github.com/runely/calendar-homey/commit/e8821b2061520aded0b3101670565735600f5d96)
