### ISSUE TITLE
Feature: adjust the update interval

### ISSUE THREAD

**Issue by tkroon89** [runely/calendar-homey#565]
Problem
At the moment the app downloads and processes all icals every 15 minutes, which causes high(er) CPU load on Homey. 

Suggested solution
I would like to be able to change the default interval time between ical updates.

**Comment by tkroon89** [comment]
Another idea: the option to only start syncing via a flow card. Since the app can be quite CPU heavy, it would be nice to automate this only when everyone is asleep, or away for example.

**Comment by runely** [comment]
This one is now live in **v 2.7.1**
