### ISSUE TITLE
Missing Remove button for the first calendar added to the app

### ISSUE THREAD

**Issue by jarll** [runely/calendar-homey#578]
**Describe the bug**
There is no "remove" button for the first calendar added to the APP. There is for the second/third etc.

**To Reproduce**
1. Install IcalCalendar
2. Open IcalCalendar -> settings
3. Add a calendar and press save
4. Exit the APP settings
5. Re-open IcalCalendar settings and observe that a new calendar can be added, but the first can not be removed

**Expected behavior**
A "Remove" button on the first calendal added in the APP settings

**Workaround**
Reinstall the APP

**Homey:**
 - Firmware: Homey Pro (Early 2019) v 10.0.7
 - IcalCalendar version: 2.6.2

**Comment by runely** [comment]
That is by design. If you want to remove the first (last?) calendar, remove the content of the text fields and hit save!

**Comment by jarll** [comment]
Ups. I didn't test just editing the text fields. Works. Thanks.
