### ISSUE TITLE
Add more variables to "Event is changed" When-card

### ISSUE THREAD

**Issue by EsbenRasmussen** [runely/calendar-homey#580]
Hi Runely

Thanks for the calendar integration.

I am trying to create a flow for creating reminders to myself, which will be read aloud by our Sonos, when I arrive home.

I already have a flow for ordinary recurring events which adds events to a persons to-do list based on events starting in 12 hours. This to-do list is read aloud when the person arrives home and the list is reset at 01:00 every night.

Now I want a flow for "spontaneous reminders" - which basicly are single off events, usually created during the day (so less than 12 hours ahead) where the title begins with "Reminder: ".

So a reminder event title would be structured like this: "Reminder: call insurance + follow up on invitation sent last week"

I have built a flow which listens for "Events added to persons calendar" and adds the title (minus the "Reminder: ") to a text variable. This works fine.

However, I realized that if I add more stuff to the existing reminder (by adding more to the title after the initial "Reminder: ") I am not able to validate that the date for the changed event equals today, since "start date" is not available for "Event is changed".

Instead of deleting the reminder-event in the calendar and adding a new reminder-event, the ideal solution would of course be to just update the existing - but in doing so I still need to verify that the updated event is for today.

Would it be possible to add the "start date" (and ideally also "start time") variable for the "Event is changed in calendar" card and if not, do you have a suggestion on how to confirm that the changed event happens today?

![homey-startdate-event-changed](https://github.com/runely/calendar-homey/assets/142941603/f33d134c-5a3b-42df-9d19-fe4df52f054a)

**Comment by runely** [comment]
Hi there. Sorry for taking so long to respond. A lot going on at the moment.

I've added `Start date`, `Start time`, `End date` and `End time` to event changed triggers. This comes out in the next release, **v2.8.0**
