### ISSUE TITLE
time zones

### ISSUE THREAD

**Issue by petermartis** [runely/calendar-homey#581]
Hey Rune,

Not sure if this is a bug report or feature request but all the meeting times retrieved via your plugin appear to start in their original time + time time difference to the time zone I'm. So while I'm based in Central Europe, the meeting that took place at 13:30 my time (which is 7:30 EST) appears (from your app) to be starting at 19:30 (so the time difference seems to be added (+6h) rather than subtracted (-6h)). Am I doing something wrong? 

Thanks a lot,

Peter

.0

**Comment by runely** [comment]
To see what's going on I'll need a diagnostics report. Please follow these steps:

1. Make sure you have the lastest version of the app installed
1. Make sure you have updated your Homey firmware to the latest
1. Open the settings page for the app
1. Scroll down to the bottom and enable `Log all events` (blue checkmark)
1. Click **Save**
1. Restart the app
1. Wait 5 minutes
1. Click `Create diagnostics report` on the app gear icon.
1. Copy the report id given
1. Paste the report id here

**Comment by petermartis** [comment]
Thanks Rune.  Here is the report id: 9f7e4779-46a5-455c-b766-e9c0203d9c67

Thanks again!

pm

**Comment by runely** [comment]
The diagnostics report didn't contain all the information i needed. Could you please send a new diagnostics report?

**Comment by petermartis** [comment]
I did send you another one (8839f4f0-5b73-483b-a22a-111cdac2a5f9) - now used several flow cards (next meeting, meetings tomorrow) so you should be able to see enough details (I hope).
 Thanks!

**Comment by runely** [comment]
It seems like your events, or at least some of the events, are created in America/New_York timezone while you are located in Europe/Bratislava timezone. I have no experience with this, nor any way to test this.

**Comment by petermartis** [comment]
You are right- I’m based in Bratislava and most of my events (invites) are created by people in different timezones). Testing it is easy - each invite/ical/ics contains the GMT time zone of the invite - from that you can calculate the actual time in your location (system setting will tell you that or you can have it as a configurable parameter). 

But I understand this is hobby project and your time is limited. I appreciate you’ve done this plugin - it’s been really helpful!

Thanks,

Peter

On 24 Mar 2024, at 13:40, Rune Moskvil Lyngås ***@***.***> wrote:


It seems like your events, or at least some of the events, are created in America/New_York timezone while you are located in Europe/Bratislava timezone. I have no experience with this, nor any way to test this.

**Comment by runely** [comment]
I created an event in my own google calendar with New York timezone.

The event in my google calendar and the event synced in with IcalCalendar shows the event has the same start and end time.

So I'm sorry. I can't reproduce this

**Comment by petermartis** [comment]
I understand. I honestly appreciate your trying. 

The time zone issue seems to related only those appointments, that created under timezones senttings so when you swith to your home time sone or to the time zone you're travelling into, that it reamains out of sync (time wise). 

If you need a video recording of how exactly does than happen or an access to my calendar, I'll be happy to help with that...

Best,

Peter

On 4/13/2024 11:22:23 PM, Rune Moskvil Lyngås ***@***.***> wrote:
I created an event in my own google calendar with New York timezone.
The event in my google calendar and the event synced in with IcalCalendar shows the event has the same start and end time.
So I'm sorry. I can't reproduce this

**Comment by runely** [comment]
Well, as i said. I created an event in my own google calendar with New York timezone, and it was parsed correctly in IcalCalendar.

So i can't reproduce this
