### ISSUE TITLE
Bug: Tag choices not available on advanced flow?

### ISSUE THREAD

**Issue by bvaughn1971** [runely/calendar-homey#588]
I am not sure if this is a bug or user error. On the advanced flow I can't seem to customize the tags in the card, like I can in the regular flow.  I start the flow and I don't see the customizable fields pop up, for example, Status or Location.

![image](https://github.com/runely/calendar-homey/assets/127080645/f9bf57d5-29ea-41a1-839b-652199300d33)

Thank you,
Bobby

**Comment by runely** [comment]
The list of tags, as described above the list, will be filled out with information from the card and available when the card starts.

To customize the properties/arguments for the card, click on each property/argument and change it. The properties/arguments in this card will be **5** and **Minute(s)**

**Comment by bvaughn1971** [comment]
Oh, okay. I thought all the arguments were available for every card. Now I understand. Thanks!

**Comment by runely** [comment]
All arguments in all cards are available. But the list you see here is a list of tags which is read only variables available in the flow when the card starts.

Arguments is the input to the card.
Tags are output from the card to be used in the flow
