### ISSUE TITLE
(Maybe) a new bug since last release?

### ISSUE THREAD

**Issue by PaddyPop** [runely/calendar-homey#596]
Hello,

Since last release I get A LOT of "new" added or updated events even though they are NOT new or updated.
It's to the extent that Homey will shut down the logging (error rate limit).
Restarted app and Homey 10 times.

I really like the app by the way! :-)

Many thanks!

**Comment by runely** [comment]
Hi there. There's no change in the logic for any triggers in the last release! The last release only added 4 extra tokens on the triggers `Event changed` and `Event changed in calendar`.

If it happens again, send me a diagnostics report right after it happend. Without a recent diagnostics report i have no clue what **IcalCalendar** reads out from your calendar.

Please make sure that you have followed each of the 10 steps in this guide before submitting a diagnostics report: https://community.homey.app/t/app-pro-icalcalendar/80708
