### ISSUE TITLE
After update to v0.1.1 error on loading agenda’s

### ISSUE THREAD

**Issue by RobHomey** [runely/calendar-homey#61]
Failed to load .ics file(s):
Agenda Prive: Error: 403 Forbidden
Agenda Sprinkler: Error: 400 Bad Request

**Comment by runely** [comment]
Hi Rob.

Sorry about that, and thanks for the feedback. I will look into it.

**Comment by RobHomey** [comment]
Thank you that you will look into this issue. What I saw after the update is that the webcal:// is automatically replaced by https:// when you save the calendar. I am not sure if this change has something to do with issue. Normally I do the replacement. If you want me to test something, please let me know. ☺️

**Comment by RobHomey** [comment]
I have learned via Homey forum that more people have sync issues since last update to V0.1.1. I have let them know that I already contacted the developer to fix the bug.

**Comment by runely** [comment]
Thank you 👍

**Comment by runely** [comment]
Apple calendar urls are case sensative. So when the app made the url all lower case it wasn't valid anymore...
I will bump the app to a new version to night, would it be ok if i sent you the link to the test version so you could verify that it works at your end before publishing it?

**Comment by RobHomey** [comment]
Good to hear that you found the solution to the problem. You always may send me the link for testing.

**Comment by runely** [comment]
Here's the link to the new test version. Please let me know if this also fixes the issue at your end.

For it to work you need to replace the Apple calendar url in Settings with a fresh new one (which is not lower cased...)

**Comment by RobHomey** [comment]
I did sone tests and multiple Apple calendars are working fine. 
I am very happy that I am able again to use the app. 

During some test I have seen a smal typo. I wrote somewhere Kalender with a capital K. What do you suggest regarding updates of typo's and additions?

**Comment by runely** [comment]
That's good!

Which file and I can correct it in the next version

**Comment by runely** [comment]
> I have learned via Homey forum that more people have sync issues since last update to V0.1.1. I have let them know that I already contacted the developer to fix the bug.

V0.1.3 is now live. To fix the Apple calendar issue you need to replace the Apple calendar url in Settings with a fresh new one (which is not lower cased...).

Would you be so kind to tell the people on the Homey forum? 👍

**Comment by RobHomey** [comment]
I already did. 😉
I think you made al lot of people very happy with this update. ☺️

There is one questions for all about a functionality dat is not completely clear.
Does the app sync automatically every 15 minutes and besides that you have the possibility to sync manually via a flow card?

**Comment by runely** [comment]
Yes, that’s right! That part is not documented! I'll add it to the README on the next version!
