### ISSUE TITLE
Feature: another "if" card: if an event starts within [number] [type] from [calender]

### ISSUE THREAD

**Issue by florisvanvredendaal** [runely/calendar-homey#619]
**Is your feature request related to a problem? Please describe.**
I have multiple Calendars active. I would like to create Flow when an event happens within a certain calendar.

So ideally the if in the flow would look like:

If event starts within [60] [minutes] from [sauna] calendar

**Describe the solution you'd like**

I would like to start a flow 60 minutes before the event in my sauna calendar happens. And I want to confirm it on a notification from Homey. How would you achieve this @runely? I currently tried the screenshot below, but it does not work:

![image](https://github.com/user-attachments/assets/2ec48095-a56e-4227-b410-529b2749d79a)

**Comment by runely** [comment]
You can do this already by combining a trigger card and a logic condition card like this: 

![image](https://github.com/user-attachments/assets/62c081bd-1d0a-4a5e-abbf-e8285d1811f3)
