### ISSUE TITLE
Bug: Short descriptive bug title here

### ISSUE THREAD

**Issue by PaddyPop** [runely/calendar-homey#622]
Hi,

I enjoy your app a lot but recently I have had 2 issues, where 1 remains:

First problem was that no push of new or changed events happened. Then they did get synced but now new/changed events (the last 2 or 3 events) keeps on getting added in Homey.

Thanks!

**Troubleshooting steps prior to submitting this bug**

- [x] 1. Make sure you have the lastest version of the app installed
- [x] 2. Make sure you have updated your Homey firmware to the latest
- [x] 3. Open the settings page for the IcalCalendar app
- [x] 4. Scroll down to the bottom and enable Log all events (blue checkmark)
- [x] 5. Click Save
- [x] 6. Restart the app
- [x] 7. Wait 5 minutes
- [x] 8. Click Create diagnostics report on the app gear icon.
- [x] 9. Copy the report id given: **89a94893-ee26-45ea-9cfc-f60be32dd2e7**
- [x] 10. Paste the report id in this bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Homey:**
 - Firmware: **12.2.0**
 - IcalCalendar version: **v2.10.0**
 - Calendar provider (Gmail, Office365, Apple, ...): **Gmail (Google calendar)**

**Additional context**

**Comment by PaddyPop** [comment]
Hi again Rune,

Short background: I have used Homey 2019 Pro and your app a few years now
and it has always worked. The flows I'm using are old and reliable, this
has started to happen recently so I guess it is either Google Calendar
(then I guess more should complain?) or the updated app maybe?

Last night when I was a sleep the app notified about the same event (that
was already created and synced the day before) 9 times (no repeated pattern
for time).
My flows that check for some special events in my calendars all work
fine.But the flow below (Event added) are fired many many times during a
day or so.


[image: image.png]

Hit count:

[image: image.png]

My settings:
[image: image.png]
[image: image.png]

Thank you!

//Patrik

**Comment by runely** [comment]
Attachments does not work on GitHub when sent by email. Please post your screenshots directly on GitHub.

The trigger `Event added` has not been updated in over 1 year.

The trigger `Event changed` got added two more tokens in the last update.

My flows for `Event added` and `Event changed` are also old, several years probably, and they work as they should.

If your flows are fired more frequently than you expect, i suspect there's something happening in your calendar.



Please post your screenshots again through GitHub. And if your flows are triggered more than you expect again, send me a diagnostics report no more than a couple of minutes after they triggered, so i can take a look

**Comment by PaddyPop** [comment]
Hi again, adding my screen shots!

![events](https://github.com/user-attachments/assets/825ebd83-dfef-44b4-b8ac-671ae76f0192)
![hitcounts](https://github.com/user-attachments/assets/a74914e6-bbf6-4ff0-b528-c63054cf0901)
![settings1](https://github.com/user-attachments/assets/98bcfb98-a64b-4a1b-ad7f-6585e9504017)
![settings2](https://github.com/user-attachments/assets/7235dbae-77f1-40f0-9c1e-4db442e7e4bd)
Thank you!

**Comment by runely** [comment]
You have crazy many `Synchronization errors occured` 😮 If that has anything to do with it, i don't know, but you should check whats wrong with your calendar/provider.

When a synchronization error occures, the trigger card `Synchronization error occured` is triggered containing a token with the error message. Also the error message will be shown in the bottom of the settings page of **IcalCalendar**.

**Comment by PaddyPop** [comment]
OK, weird, I will start logging the Sync errors and will let you know in a
few days ago! Thanks!

**Comment by PaddyPop** [comment]
Hello again,

So I looked further for the error message for my synchronization errors.
It's due to unstable network (EHOSTUNREACH...).
I'm curious, would this somehow trigger a lot of duplicate syncs? I'm
trying to understand why my unstable network triggers getting the same
event added from google calendar to Homey repeatedly.

Many thanks!

**Comment by runely** [comment]
If you receive EHOSTUNREACH `IcalCalendar` isn't able to get your calendar ics content and sync will not succeed.

`IcalCalendar` is built to treat an event as new when the UID of the event isn't already synced in and the CREATED property is less than 24 hours ago.

So I'm guessing that the new event added triggers you receive is because of new UID's. But the only way I can check is if you send a diagnostic report at least two times with the same event.

**Comment by PaddyPop** [comment]
Hi!

So if I try to recreate this by adding a new event and then see if it
duplicates, maybe it will happen in a few hours (first add then the
duplicate), is that too long for investigating the logs or should that work?

Thanks

**Comment by runely** [comment]
Send a diagnostics report each time the same event is triggered

**Comment by PaddyPop** [comment]
By the way, would it be possible in the future to have an card Event
is *EXACTLY
*in parallell with Event *Contains*? :-)

Thanks!

**Comment by runely** [comment]
You can use the Logic cards with the tokens from the trigger card to accomplish this

**Comment by PaddyPop** [comment]
I tried but I cannot find any token from the trigger card. Now, my flow is
to check some calendars for some value at early morning, like this:
[image: bild.png]

**Comment by runely** [comment]
All trigger cards in `IcalCalendar` has tokens containing info about the event it was triggered for.

When you click a token label (like the one in the Logic AND card) it will show you a list of all available tokens on your Homey, and the first section, called **This Flow**, will have the tokens from the current trigger card

![Skjermbilde 2024-12-09 084754](https://github.com/user-attachments/assets/f2d15c62-cf57-49b6-8ba2-065bb44e8b83)

![Skjermbilde 2024-12-09 090936](https://github.com/user-attachments/assets/fc75c3c6-e43d-47ce-b0ed-1af64c42582e)

![Skjermbilde 2024-12-09 091050](https://github.com/user-attachments/assets/61fb8409-8117-4e9c-8e47-5c72db51a157)

**Comment by PaddyPop** [comment]
oops, forgot the screenshot, like this:

[image: bild.png]

**Comment by runely** [comment]
Still, attachments doesn't work through email..

And no, condition cards can't have tokens

**Comment by PaddyPop** [comment]
H again Rune,

I tried to provoke an event error now. Yesterday I created an event for
this test. It was synced now, like 20h late.
The diagnostic id is ce837340-9543-49bc-bc04-f454f25b25e8

As soon as the duplicate will appear, I send another dia-id!

Thanks!

**Comment by runely** [comment]
What is the name of the event? And at what tim and timezone did you create the event for?

**Comment by runely** [comment]
And which calendar name did you add the event in?

**Comment by runely** [comment]
There's something fishy with you network or something, because the app are having trouble randomly to reach all three of your added calendars. Sometimes it can reach the URL, and sometimes not.

I'm guessing network issues or some other external (not app related) issues.

**Comment by PaddyPop** [comment]
Second event - the duplicate came now - dia id:
fe05c113-d5d1-424e-b529-3084bd1e7fdb
The Event is called TestFirstUniqueEventForHomey
The calendar is called Paddy Google Calendar
It is a all-day event for the 21 of December. The timezone is
Stockholm/Sweden.

I think its the network, it is (nowadays) very unstable somehow. Its Mesh,
TPlink Deco.

Thanks!

**Comment by PaddyPop** [comment]
Hi Rune, last question please:

Did you see a new UID for event TestFirstUniqueEventForHomey?
Just trying to understand this.

Thanks!

**Comment by runely** [comment]
Hi.

No, the event is not created with a different UID.

However, i have managed to kind of recreate this behavior and this is happening because of your network issues.

When **IcalCalendar** downloads the calendar events, it keeps track of the synced in events and their UID's.
When the calendar isn't reachable for some reason, the synced events UID's isn't retained since the calendar isn't reached and they are wiped.

So when the calendar is reached again, the events and their UID's are kept track of, but since the UID's isn't known, it treat the events as new events.

So I'm gonna close this issue now since this is a network related issue, and not an app issue.

**Comment by PaddyPop** [comment]
Thank you so much for explaining this, I will try to fix my network then!
:-)
Merry Christmas!
