### ISSUE TITLE
Not a Bug: Cannot save flow

### ISSUE THREAD

**Issue by 4braincells** [runely/calendar-homey#625]
I installed the app, created a new cal with one event XYZ,
added a AND-consdition "EVENT XYZ ONGOING", 
connected it,
tested it (seems to work!) ...
but I cannot SAVE the FLOW.
Error:  "invalid arguments"

**Homey:**
 - Firmware: current per to-day
 - IcalCalendar version: current per to-day
 - Calendar provider (Gmail, Office365, Apple, ...):  apple

What's wrong here?

**Comment by runely** [comment]
Please add a screenshot of your flow and a screenshot of the error message you are receiving.

With that said, saving a flow, no matter which cards you have added, is all Homey related and has nothing to do with any of the apps.

**Comment by 4braincells** [comment]
Your are right. I am wrong. And homey didn't tell me the truth.

There is a post in the forum which helped me.
This connects with me having updated homey OS today. 
Until this update the time events accepted an event "Sunrise in -20" which triggered 20 mins before sunrise.
This is now marked as an error when I change minor things in the flow e.g. position of some object.

But when I added the iCal condition, homey just popped up the error message "invalid arguments", 
but NONE of the boxes were highlighted. 
Thus I didn't see where where problem came from.
So I shot the messenger. Sorry :-)
